import { GAME_ICONS_ABSTRACT } from './gameIconsAbstract'

export interface IconEntry {
  name: string // display label
  lucide: string // Lucide component name (PascalCase); '' for svg-only entries
  svg?: string // inner SVG content (paths/shapes, no wrapper); used instead of lucide when present
  keywords: string[] // for search
  category: string
  /** Native coordinate system for SVG-only entries (defaults to 0 0 24 24). */
  viewBox?: string
  /** Third-party source used for rendering semantics and attribution. */
  source?: 'game-icons'
}

export const ICON_CATEGORIES = [
  'Abstract',
  'Business',
  'People',
  'Remote Work',
  'Help & Support',
  'Technology',
  'Location',
  'Communication',
  'Security',
  'Finance',
  'Commerce',
  'Health',
  'Education',
  'Tools',
  'Design',
  'Media',
  'Social',
  'Nature',
  'Food & Drink',
  'Travel',
  'Productivity',
  'Navigation'
] as const

export const ICON_LIBRARY: IconEntry[] = [
  // ── Abstract (114 icons) ──────────────────────────────────────────────────────
  // Geometric shapes
  { name: 'Circle', lucide: 'Circle', keywords: ['circle', 'round', 'ring', 'shape', 'geometric'], category: 'Abstract' },
  { name: 'Triangle', lucide: 'Triangle', keywords: ['triangle', 'delta', 'shape', 'geometric', 'sharp'], category: 'Abstract' },
  { name: 'Square', lucide: 'Square', keywords: ['square', 'box', 'shape', 'geometric'], category: 'Abstract' },
  { name: 'Hexagon', lucide: 'Hexagon', keywords: ['hexagon', 'hex', 'honeycomb', 'geometric'], category: 'Abstract' },
  { name: 'Pentagon', lucide: 'Pentagon', keywords: ['pentagon', 'five', 'shape', 'geometric'], category: 'Abstract' },
  { name: 'Octagon', lucide: 'Octagon', keywords: ['octagon', 'eight', 'stop', 'geometric'], category: 'Abstract' },
  { name: 'Diamond', lucide: 'Diamond', keywords: ['diamond', 'rhombus', 'gem', 'geometric'], category: 'Abstract' },
  { name: 'Star', lucide: 'Star', keywords: ['star', 'polygon', 'five', 'radial', 'shape'], category: 'Abstract' },
  { name: 'Snowflake', lucide: 'Snowflake', keywords: ['snowflake', 'crystal', 'fractal', 'radial', 'symmetry'], category: 'Abstract' },
  { name: 'RectangleHorizontal', lucide: 'RectangleHorizontal', keywords: ['rectangle', 'wide', 'landscape', 'shape', 'geometric'], category: 'Abstract' },
  { name: 'RectangleVertical', lucide: 'RectangleVertical', keywords: ['rectangle', 'tall', 'portrait', 'shape', 'geometric'], category: 'Abstract' },
  { name: 'Disc', lucide: 'Disc', keywords: ['disc', 'circle', 'round', 'flat'], category: 'Abstract' },
  { name: 'Disc2', lucide: 'Disc2', keywords: ['disc', 'ring', 'circle', 'vinyl'], category: 'Abstract' },
  { name: 'Disc3', lucide: 'Disc3', keywords: ['disc', 'dot', 'circle', 'optical'], category: 'Abstract' },
  // Symbols & math
  { name: 'Infinity', lucide: 'Infinity', keywords: ['infinity', 'loop', 'endless', 'lemniscate'], category: 'Abstract' },
  { name: 'Asterisk', lucide: 'Asterisk', keywords: ['asterisk', 'star', 'symbol', 'radial'], category: 'Abstract' },
  { name: 'Hash', lucide: 'Hash', keywords: ['hash', 'grid', 'pattern', 'hashtag', 'symbol'], category: 'Abstract' },
  { name: 'Plus', lucide: 'Plus', keywords: ['plus', 'cross', 'add', 'symbol'], category: 'Abstract' },
  { name: 'Minus', lucide: 'Minus', keywords: ['minus', 'dash', 'subtract', 'bar'], category: 'Abstract' },
  { name: 'Divide', lucide: 'Divide', keywords: ['divide', 'math', 'division', 'symbol'], category: 'Abstract' },
  { name: 'Percent', lucide: 'Percent', keywords: ['percent', 'proportion', 'ratio', 'symbol'], category: 'Abstract' },
  { name: 'Equal', lucide: 'Equal', keywords: ['equal', 'same', 'balance', 'math', 'symbol'], category: 'Abstract' },
  { name: 'Ampersand', lucide: 'Ampersand', keywords: ['ampersand', 'and', 'symbol', 'typography'], category: 'Abstract' },
  { name: 'Slash', lucide: 'Slash', keywords: ['slash', 'diagonal', 'divider', 'mark'], category: 'Abstract' },
  { name: 'Pilcrow', lucide: 'Pilcrow', keywords: ['pilcrow', 'paragraph', 'mark', 'typography'], category: 'Abstract' },
  { name: 'Copyright', lucide: 'Copyright', keywords: ['copyright', 'c', 'circle', 'mark'], category: 'Abstract' },
  { name: 'Sigma', lucide: 'Sigma', keywords: ['sigma', 'sum', 'math', 'greek'], category: 'Abstract' },
  { name: 'Pi', lucide: 'Pi', keywords: ['pi', 'math', 'constant', 'greek'], category: 'Abstract' },
  { name: 'Binary', lucide: 'Binary', keywords: ['binary', '01', 'digital', 'code'], category: 'Abstract' },
  { name: 'Variable', lucide: 'Variable', keywords: ['variable', 'math', 'algebra', 'x'], category: 'Abstract' },
  { name: 'Radical', lucide: 'Radical', keywords: ['radical', 'sqrt', 'root', 'math'], category: 'Abstract' },
  { name: 'Atom', lucide: 'Atom', keywords: ['atom', 'nucleus', 'orbit', 'particle', 'science'], category: 'Abstract' },
  { name: 'Tangent', lucide: 'Tangent', keywords: ['tangent', 'curve', 'geometry', 'math'], category: 'Abstract' },
  { name: 'Regex', lucide: 'Regex', keywords: ['regex', 'pattern', 'match', 'expression'], category: 'Abstract' },
  // 3D forms
  { name: 'Orbit', lucide: 'Orbit', keywords: ['orbit', 'circular', 'path', 'rotate'], category: 'Abstract' },
  { name: 'Axis3d', lucide: 'Axis3d', keywords: ['axis', '3d', 'xyz', 'coordinate'], category: 'Abstract' },
  { name: 'Box', lucide: 'Box', keywords: ['cube', '3d', 'box', 'solid', 'geometric'], category: 'Abstract' },
  { name: 'Cylinder', lucide: 'Cylinder', keywords: ['cylinder', '3d', 'tube', 'round'], category: 'Abstract' },
  { name: 'Cone', lucide: 'Cone', keywords: ['cone', '3d', 'triangle', 'geometric'], category: 'Abstract' },
  // Code / bracket symbols
  { name: 'Braces', lucide: 'Braces', keywords: ['braces', 'curly', 'bracket', 'code'], category: 'Abstract' },
  { name: 'Brackets', lucide: 'Brackets', keywords: ['brackets', 'square', 'array', 'code'], category: 'Abstract' },
  { name: 'Parentheses', lucide: 'Parentheses', keywords: ['parentheses', 'round', 'bracket', 'group'], category: 'Abstract' },
  { name: 'Spline', lucide: 'Spline', keywords: ['spline', 'bezier', 'curve', 'path', 'smooth'], category: 'Abstract' },
  { name: 'Blend', lucide: 'Blend', keywords: ['blend', 'gradient', 'mix', 'transition', 'overlap'], category: 'Abstract' },
  // Organic / energy
  { name: 'Waves', lucide: 'Waves', keywords: ['waves', 'wave', 'flow', 'rhythm', 'oscillate'], category: 'Abstract' },
  { name: 'Sparkles', lucide: 'Sparkles', keywords: ['sparkles', 'star', 'magic', 'particle', 'shine'], category: 'Abstract' },
  { name: 'Eclipse', lucide: 'Eclipse', keywords: ['eclipse', 'overlap', 'circle', 'cosmic'], category: 'Abstract' },
  { name: 'Zap', lucide: 'Zap', keywords: ['zap', 'bolt', 'lightning', 'energy', 'electric'], category: 'Abstract' },
  { name: 'Flame', lucide: 'Flame', keywords: ['flame', 'fire', 'burn', 'energy', 'organic'], category: 'Abstract' },
  { name: 'Wind', lucide: 'Wind', keywords: ['wind', 'flow', 'lines', 'air', 'movement'], category: 'Abstract' },
  { name: 'Activity', lucide: 'Activity', keywords: ['activity', 'pulse', 'wave', 'heartbeat', 'line'], category: 'Abstract' },
  { name: 'Dna', lucide: 'Dna', keywords: ['dna', 'helix', 'spiral', 'double', 'organic'], category: 'Abstract' },
  { name: 'Vibrate', lucide: 'Vibrate', keywords: ['vibrate', 'oscillate', 'wave', 'buzz', 'frequency'], category: 'Abstract' },
  { name: 'AudioWaveform', lucide: 'AudioWaveform', keywords: ['audio', 'wave', 'sound', 'waveform', 'frequency'], category: 'Abstract' },
  // Patterns / dots / grids
  { name: 'Grip', lucide: 'Grip', keywords: ['grip', 'dots', 'grid', 'pattern', 'handle'], category: 'Abstract' },
  { name: 'GripVertical', lucide: 'GripVertical', keywords: ['grip', 'dots', 'vertical', 'pattern', 'handle'], category: 'Abstract' },
  { name: 'GripHorizontal', lucide: 'GripHorizontal', keywords: ['grip', 'dots', 'horizontal', 'pattern', 'handle'], category: 'Abstract' },
  { name: 'Dot', lucide: 'Dot', keywords: ['dot', 'point', 'particle', 'small', 'mark'], category: 'Abstract' },
  { name: 'Grid3X3', lucide: 'Grid3X3', keywords: ['grid', 'dots', 'pattern', 'nine', 'mosaic'], category: 'Abstract' },
  { name: 'SquareStack', lucide: 'SquareStack', keywords: ['stack', 'squares', 'layers', 'depth', 'pages'], category: 'Abstract' },
  { name: 'ToyBrick', lucide: 'ToyBrick', keywords: ['brick', 'block', 'lego', 'module', 'build'], category: 'Abstract' },
  { name: 'Signal', lucide: 'Signal', keywords: ['signal', 'bars', 'strength', 'wave', 'level'], category: 'Abstract' },
  // Typography symbols
  { name: 'Strikethrough', lucide: 'Strikethrough', keywords: ['strikethrough', 'cross', 'line', 'cancel'], category: 'Abstract' },
  { name: 'Subscript', lucide: 'Subscript', keywords: ['subscript', 'sub', 'math', 'chemistry'], category: 'Abstract' },
  { name: 'Superscript', lucide: 'Superscript', keywords: ['superscript', 'power', 'exponent', 'math'], category: 'Abstract' },
  { name: 'Italic', lucide: 'Italic', keywords: ['italic', 'slant', 'type', 'letter', 'style'], category: 'Abstract' },
  { name: 'Bold', lucide: 'Bold', keywords: ['bold', 'thick', 'strong', 'letter', 'type'], category: 'Abstract' },
  // Selection / targeting
  { name: 'BoxSelect', lucide: 'BoxSelect', keywords: ['select', 'box', 'region', 'area', 'frame'], category: 'Abstract' },
  { name: 'Lasso', lucide: 'Lasso', keywords: ['lasso', 'select', 'freehand', 'loop', 'curve'], category: 'Abstract' },
  { name: 'Crosshair', lucide: 'Crosshair', keywords: ['crosshair', 'target', 'aim', 'sight', 'center'], category: 'Abstract' },
  { name: 'CircleDot', lucide: 'CircleDot', keywords: ['circle', 'dot', 'target', 'point', 'focus'], category: 'Abstract' },
  { name: 'CircleDashed', lucide: 'CircleDashed', keywords: ['circle', 'dashed', 'outline', 'selection', 'ring'], category: 'Abstract' },
  { name: 'SquareAsterisk', lucide: 'SquareAsterisk', keywords: ['square', 'asterisk', 'pattern', 'symbol', 'star'], category: 'Abstract' },
  { name: 'Scan', lucide: 'Scan', keywords: ['scan', 'frame', 'corners', 'boundary', 'detect'], category: 'Abstract' },
  { name: 'ScanLine', lucide: 'ScanLine', keywords: ['scan', 'line', 'beam', 'detect', 'analyze'], category: 'Abstract' },
  { name: 'Focus', lucide: 'Focus', keywords: ['focus', 'rings', 'center', 'attention', 'zoom'], category: 'Abstract' },
  { name: 'Target', lucide: 'Target', keywords: ['target', 'bullseye', 'aim', 'rings', 'precision'], category: 'Abstract' },
  // Transform / motion
  { name: 'Move', lucide: 'Move', keywords: ['move', 'drag', 'arrows', 'direction', 'transform'], category: 'Abstract' },
  { name: 'RotateCw', lucide: 'RotateCw', keywords: ['rotate', 'spin', 'clockwise', 'turn', 'circular'], category: 'Abstract' },
  { name: 'RotateCcw', lucide: 'RotateCcw', keywords: ['rotate', 'spin', 'counter', 'reverse', 'circular'], category: 'Abstract' },
  { name: 'FlipHorizontal', lucide: 'FlipHorizontal', keywords: ['flip', 'mirror', 'horizontal', 'reflect'], category: 'Abstract' },
  { name: 'FlipHorizontal2', lucide: 'FlipHorizontal2', keywords: ['flip', 'mirror', 'horizontal', 'symmetry'], category: 'Abstract' },
  { name: 'FlipVertical', lucide: 'FlipVertical', keywords: ['flip', 'mirror', 'vertical', 'reflect'], category: 'Abstract' },
  { name: 'FlipVertical2', lucide: 'FlipVertical2', keywords: ['flip', 'mirror', 'vertical', 'symmetry'], category: 'Abstract' },
  { name: 'Maximize2', lucide: 'Maximize2', keywords: ['expand', 'maximize', 'corners', 'scale', 'grow'], category: 'Abstract' },
  { name: 'Minimize2', lucide: 'Minimize2', keywords: ['minimize', 'shrink', 'compress', 'corners', 'scale'], category: 'Abstract' },
  { name: 'Shuffle', lucide: 'Shuffle', keywords: ['shuffle', 'random', 'mix', 'cross', 'arrows'], category: 'Abstract' },
  { name: 'Repeat2', lucide: 'Repeat2', keywords: ['repeat', 'loop', 'cycle', 'circular'], category: 'Abstract' },
  { name: 'RefreshCw', lucide: 'RefreshCw', keywords: ['refresh', 'reload', 'circle', 'arrows', 'loop'], category: 'Abstract' },
  { name: 'RefreshCcw', lucide: 'RefreshCcw', keywords: ['refresh', 'reverse', 'circle', 'arrows', 'loop'], category: 'Abstract' },
  { name: 'Rewind', lucide: 'Rewind', keywords: ['rewind', 'back', 'arrows', 'reverse', 'playback'], category: 'Abstract' },
  { name: 'FastForward', lucide: 'FastForward', keywords: ['fast', 'forward', 'skip', 'arrows', 'playback'], category: 'Abstract' },
  { name: 'IterationCw', lucide: 'IterationCw', keywords: ['iteration', 'loop', 'cycle', 'clockwise'], category: 'Abstract' },
  { name: 'IterationCcw', lucide: 'IterationCcw', keywords: ['iteration', 'loop', 'cycle', 'counter'], category: 'Abstract' },
  // Directional arrows
  { name: 'ArrowLeftRight', lucide: 'ArrowLeftRight', keywords: ['arrow', 'bidirectional', 'left right', 'exchange'], category: 'Abstract' },
  { name: 'ArrowUpDown', lucide: 'ArrowUpDown', keywords: ['arrow', 'bidirectional', 'up down', 'vertical'], category: 'Abstract' },
  { name: 'ChevronsUpDown', lucide: 'ChevronsUpDown', keywords: ['chevrons', 'expand', 'collapse', 'up down'], category: 'Abstract' },
  { name: 'ChevronsLeftRight', lucide: 'ChevronsLeftRight', keywords: ['chevrons', 'expand', 'horizontal', 'left right'], category: 'Abstract' },
  { name: 'ArrowBigUp', lucide: 'ArrowBigUp', keywords: ['arrow', 'big', 'up', 'direction', 'bold'], category: 'Abstract' },
  { name: 'ArrowBigDown', lucide: 'ArrowBigDown', keywords: ['arrow', 'big', 'down', 'direction', 'bold'], category: 'Abstract' },
  { name: 'ArrowBigLeft', lucide: 'ArrowBigLeft', keywords: ['arrow', 'big', 'left', 'direction', 'bold'], category: 'Abstract' },
  { name: 'ArrowBigRight', lucide: 'ArrowBigRight', keywords: ['arrow', 'big', 'right', 'direction', 'bold'], category: 'Abstract' },
  // Layout / structure
  { name: 'AlignCenter', lucide: 'AlignCenter', keywords: ['align', 'center', 'lines', 'layout', 'symmetry'], category: 'Abstract' },
  { name: 'SeparatorHorizontal', lucide: 'SeparatorHorizontal', keywords: ['separator', 'horizontal', 'divider', 'line'], category: 'Abstract' },
  { name: 'SeparatorVertical', lucide: 'SeparatorVertical', keywords: ['separator', 'vertical', 'divider', 'line'], category: 'Abstract' },
  { name: 'SquareSplitHorizontal', lucide: 'SquareSplitHorizontal', keywords: ['split', 'divide', 'horizontal', 'layout'], category: 'Abstract' },
  { name: 'SquareSplitVertical', lucide: 'SquareSplitVertical', keywords: ['split', 'divide', 'vertical', 'layout'], category: 'Abstract' },
  { name: 'Layers', lucide: 'Layers', keywords: ['layers', 'stack', 'depth', 'levels', 'structure'], category: 'Abstract' },
  { name: 'Diff', lucide: 'Diff', keywords: ['diff', 'compare', 'delta', 'change', 'plus minus'], category: 'Abstract' },
  // Data / graph
  { name: 'Network', lucide: 'Network', keywords: ['network', 'nodes', 'graph', 'connect', 'web'], category: 'Abstract' },
  { name: 'GitGraph', lucide: 'GitGraph', keywords: ['graph', 'nodes', 'branch', 'flow', 'network'], category: 'Abstract' },
  { name: 'ScatterChart', lucide: 'ScatterChart', keywords: ['scatter', 'chart', 'data', 'points', 'plot'], category: 'Abstract' },
  { name: 'CandlestickChart', lucide: 'CandlestickChart', keywords: ['candlestick', 'chart', 'data', 'bars'], category: 'Abstract' },
  // Misc abstract
  { name: 'Hourglass', lucide: 'Hourglass', keywords: ['hourglass', 'time', 'sand', 'wait', 'shape'], category: 'Abstract' },
  // More Lucide abstract — motion / shape variants
  { name: 'MoveUp', lucide: 'MoveUp', keywords: ['move', 'up', 'arrow', 'direction', 'lift'], category: 'Abstract' },
  { name: 'MoveDown', lucide: 'MoveDown', keywords: ['move', 'down', 'arrow', 'direction', 'drop'], category: 'Abstract' },
  { name: 'MoveLeft', lucide: 'MoveLeft', keywords: ['move', 'left', 'arrow', 'direction'], category: 'Abstract' },
  { name: 'MoveRight', lucide: 'MoveRight', keywords: ['move', 'right', 'arrow', 'direction'], category: 'Abstract' },
  { name: 'MoveUpLeft', lucide: 'MoveUpLeft', keywords: ['move', 'diagonal', 'up left', 'arrow'], category: 'Abstract' },
  { name: 'MoveUpRight', lucide: 'MoveUpRight', keywords: ['move', 'diagonal', 'up right', 'arrow'], category: 'Abstract' },
  { name: 'MoveDownLeft', lucide: 'MoveDownLeft', keywords: ['move', 'diagonal', 'down left', 'arrow'], category: 'Abstract' },
  { name: 'MoveDownRight', lucide: 'MoveDownRight', keywords: ['move', 'diagonal', 'down right', 'arrow'], category: 'Abstract' },
  { name: 'MoveHorizontal', lucide: 'MoveHorizontal', keywords: ['move', 'horizontal', 'resize', 'expand'], category: 'Abstract' },
  { name: 'MoveVertical', lucide: 'MoveVertical', keywords: ['move', 'vertical', 'resize', 'expand'], category: 'Abstract' },
  { name: 'Expand', lucide: 'Expand', keywords: ['expand', 'fullscreen', 'grow', 'scale', 'maximize'], category: 'Abstract' },
  { name: 'Shrink', lucide: 'Shrink', keywords: ['shrink', 'minimize', 'compress', 'scale', 'small'], category: 'Abstract' },
  { name: 'StretchHorizontal', lucide: 'StretchHorizontal', keywords: ['stretch', 'wide', 'horizontal', 'extend'], category: 'Abstract' },
  { name: 'StretchVertical', lucide: 'StretchVertical', keywords: ['stretch', 'tall', 'vertical', 'extend'], category: 'Abstract' },
  { name: 'CircleX', lucide: 'CircleX', keywords: ['circle', 'x', 'close', 'cancel', 'remove'], category: 'Abstract' },
  { name: 'CirclePlus', lucide: 'CirclePlus', keywords: ['circle', 'plus', 'add', 'expand', 'create'], category: 'Abstract' },
  { name: 'CircleMinus', lucide: 'CircleMinus', keywords: ['circle', 'minus', 'remove', 'subtract'], category: 'Abstract' },
  { name: 'CircleSlash', lucide: 'CircleSlash', keywords: ['circle', 'slash', 'forbidden', 'no', 'ban'], category: 'Abstract' },
  { name: 'SquarePlus', lucide: 'SquarePlus', keywords: ['square', 'plus', 'add', 'new', 'create'], category: 'Abstract' },
  { name: 'SquareMinus', lucide: 'SquareMinus', keywords: ['square', 'minus', 'remove', 'subtract'], category: 'Abstract' },
  { name: 'SquareX', lucide: 'SquareX', keywords: ['square', 'x', 'close', 'cancel', 'clear'], category: 'Abstract' },
  { name: 'SquareDivide', lucide: 'SquareDivide', keywords: ['square', 'divide', 'split', 'math'], category: 'Abstract' },
  { name: 'Undo', lucide: 'Undo', keywords: ['undo', 'back', 'reverse', 'history', 'arrow'], category: 'Abstract' },
  { name: 'Redo', lucide: 'Redo', keywords: ['redo', 'forward', 'repeat', 'history', 'arrow'], category: 'Abstract' },
  { name: 'Undo2', lucide: 'Undo2', keywords: ['undo', 'back', 'arrow', 'reverse', 'curved'], category: 'Abstract' },
  { name: 'Redo2', lucide: 'Redo2', keywords: ['redo', 'forward', 'arrow', 'curved', 'repeat'], category: 'Abstract' },
  { name: 'CornerDownLeft', lucide: 'CornerDownLeft', keywords: ['corner', 'down left', 'turn', 'enter', 'arrow'], category: 'Abstract' },
  { name: 'CornerDownRight', lucide: 'CornerDownRight', keywords: ['corner', 'down right', 'turn', 'arrow'], category: 'Abstract' },
  { name: 'CornerUpLeft', lucide: 'CornerUpLeft', keywords: ['corner', 'up left', 'turn', 'arrow'], category: 'Abstract' },
  { name: 'CornerUpRight', lucide: 'CornerUpRight', keywords: ['corner', 'up right', 'turn', 'arrow'], category: 'Abstract' },
  { name: 'GitCommit', lucide: 'GitCommit', keywords: ['node', 'point', 'dot', 'commit', 'circle line'], category: 'Abstract' },
  { name: 'GitFork', lucide: 'GitFork', keywords: ['fork', 'branch', 'split', 'diverge', 'y shape'], category: 'Abstract' },
  { name: 'GitCompare', lucide: 'GitCompare', keywords: ['compare', 'arrows', 'cycle', 'exchange'], category: 'Abstract' },
  { name: 'Hand', lucide: 'Hand', keywords: ['hand', 'stop', 'gesture', 'palm', 'wave', 'halt'], category: 'Abstract' },
  { name: 'Pointer', lucide: 'Pointer', keywords: ['pointer', 'cursor', 'click', 'hand', 'select'], category: 'Abstract' },
  { name: 'Diameter', lucide: 'Diameter', keywords: ['diameter', 'circle', 'measure', 'geometry', 'math'], category: 'Abstract' },
  { name: 'Table', lucide: 'Table', keywords: ['table', 'grid', 'rows', 'columns', 'data', 'spreadsheet'], category: 'Abstract' },
  { name: 'TableCellsMerge', lucide: 'TableCellsMerge', keywords: ['merge', 'cells', 'table', 'combine', 'grid'], category: 'Abstract' },
  { name: 'TableCellsSplit', lucide: 'TableCellsSplit', keywords: ['split', 'cells', 'table', 'divide', 'grid'], category: 'Abstract' },
  { name: 'Scale3d', lucide: 'Scale3d', keywords: ['scale', '3d', 'transform', 'resize', 'three'], category: 'Abstract' },
  { name: 'CaseSensitive', lucide: 'CaseSensitive', keywords: ['case', 'letter', 'type', 'abc', 'text'], category: 'Abstract' },
  // Custom SVG icons — mathematical symbols & unique geometric forms not in Lucide
  {
    name: 'Omega',
    lucide: '',
    svg: '<path d="M7 19C7 12.4 9.2 7 12 7C14.8 7 17 12.4 17 19"/><line x1="7" y1="19" x2="7" y2="21"/><line x1="17" y1="19" x2="17" y2="21"/><line x1="5" y1="21" x2="9" y2="21"/><line x1="15" y1="21" x2="19" y2="21"/>',
    keywords: ['omega', 'greek', 'letter', 'math', 'last', 'end'],
    category: 'Abstract'
  },
  {
    name: 'Phi',
    lucide: '',
    svg: '<circle cx="12" cy="12" r="7"/><line x1="12" y1="2" x2="12" y2="22"/>',
    keywords: ['phi', 'golden', 'ratio', 'greek', 'letter', 'math', 'circle line'],
    category: 'Abstract'
  },
  {
    name: 'Theta',
    lucide: '',
    svg: '<ellipse cx="12" cy="12" rx="8" ry="10"/><line x1="4" y1="12" x2="20" y2="12"/>',
    keywords: ['theta', 'greek', 'letter', 'angle', 'math', 'ellipse'],
    category: 'Abstract'
  },
  {
    name: 'Integral',
    lucide: '',
    svg: '<path d="M14 4C14 2.9 13.1 2 12 2S10 2.9 10 4V20C10 21.1 9.1 22 8 22S6 21.1 6 20"/>',
    keywords: ['integral', 'calculus', 'math', 's curve', 'area', 'sum'],
    category: 'Abstract'
  },
  {
    name: 'SineWave',
    lucide: '',
    svg: '<path d="M2 12C4 4 7 4 8 12C9 20 12 20 14 12C15 4 18 4 20 12"/>',
    keywords: ['sine', 'wave', 'oscillate', 'frequency', 'periodic', 'smooth'],
    category: 'Abstract'
  },
  {
    name: 'Torus',
    lucide: '',
    svg: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/>',
    keywords: ['torus', 'donut', 'ring', 'hole', '3d', 'concentric'],
    category: 'Abstract'
  },
  {
    name: 'VennDiagram',
    lucide: '',
    svg: '<circle cx="9" cy="12" r="7"/><circle cx="15" cy="12" r="7"/>',
    keywords: ['venn', 'overlap', 'intersect', 'union', 'set', 'diagram'],
    category: 'Abstract'
  },
  {
    name: 'Spiral',
    lucide: '',
    svg: '<path d="M12 12C14 9 18 10 18 13C18 17 13 20 9 19C5 18 3 14 5 10C7 6 12 4 17 6C22 8 22 13 19 18"/>',
    keywords: ['spiral', 'swirl', 'coil', 'vortex', 'rotate', 'grow'],
    category: 'Abstract'
  },

  // ── Abstract: Tabler Icons (react-icons/tb) — 24x24 stroke, same style as Lucide ──
  { name: 'OmegaGlyph', lucide: '', svg: '<path d="M4 19h5v-1a7.35 7.35 0 1 1 6 0v1h5"></path>', keywords: ['omega', 'greek', 'letter', 'math', 'last', 'end', 'symbol'], category: 'Abstract' },
  { name: 'MathIntegral', lucide: '', svg: '<path d="M7 19a2 2 0 0 0 2 2c2 0 2 -4 3 -9s1 -9 3 -9a2 2 0 0 1 2 2"></path>', keywords: ['integral', 'calculus', 'math', 'area', 's curve', 'sum'], category: 'Abstract' },
  { name: 'MathPi', lucide: '', svg: '<path d="M7 20v-16"></path><path d="M17 4v16"></path><path d="M20 4h-16"></path>', keywords: ['pi', 'math', 'constant', 'greek', 'symbol'], category: 'Abstract' },
  { name: 'MathFunction', lucide: '', svg: '<path d="M3 19a2 2 0 0 0 2 2c2 0 2 -4 3 -9s1 -9 3 -9a2 2 0 0 1 2 2"></path><path d="M5 12h6"></path><path d="M15 12l6 6"></path><path d="M15 18l6 -6"></path>', keywords: ['function', 'math', 'formula', 'f(x)', 'equation'], category: 'Abstract' },
  { name: 'MathSymbols', lucide: '', svg: '<path d="M3 12l18 0"></path><path d="M12 3l0 18"></path><path d="M16.5 4.5l3 3"></path><path d="M19.5 4.5l-3 3"></path><path d="M6 4l0 4"></path><path d="M4 6l4 0"></path><path d="M18 16l.01 0"></path><path d="M18 20l.01 0"></path><path d="M4 18l4 0"></path>', keywords: ['symbols', 'math', 'operators', 'plus minus', 'formula'], category: 'Abstract' },
  { name: 'Atom2', lucide: '', svg: '<path d="M12 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path><path d="M12 21l0 .01"></path><path d="M3 9l0 .01"></path><path d="M21 9l0 .01"></path><path d="M8 20.1a9 9 0 0 1 -5 -7.1"></path><path d="M16 20.1a9 9 0 0 0 5 -7.1"></path><path d="M6.2 5a9 9 0 0 1 11.4 0"></path>', keywords: ['atom', 'nucleus', 'science', 'orbital', 'variant'], category: 'Abstract' },
  { name: 'Dna2', lucide: '', svg: '<path d="M17 3v1c-.01 3.352 -1.68 6.023 -5.008 8.014c-3.328 1.99 3.336 -2 .008 -.014c-3.328 1.99 -5 4.662 -5.008 8.014v1"></path><path d="M17 21.014v-1c-.01 -3.352 -1.68 -6.023 -5.008 -8.014c-3.328 -1.99 3.336 2 .008 .014c-3.328 -1.991 -5 -4.662 -5.008 -8.014v-1"></path><path d="M7 4h10"></path><path d="M7 20h10"></path><path d="M8 8h8"></path><path d="M8 16h8"></path>', keywords: ['dna', 'helix', 'genetics', 'biology', 'double strand'], category: 'Abstract' },
  { name: 'Sphere', lucide: '', svg: '<path d="M3 12c0 1.657 4.03 3 9 3s9 -1.343 9 -3"></path><path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>', keywords: ['sphere', '3d', 'ball', 'round', 'planet'], category: 'Abstract' },
  { name: 'Prism', lucide: '', svg: '<path d="M12 9v13"></path><path d="M19 17.17l-5.98 4.485a1.7 1.7 0 0 1 -2.04 0l-5.98 -4.485a2.5 2.5 0 0 1 -1 -2v-11.17a1 1 0 0 1 1 -1h14a1 1 0 0 1 1 1v11.17a2.5 2.5 0 0 1 -1 2z"></path><path d="M4.3 3.3l6.655 5.186a1.7 1.7 0 0 0 2.09 0l6.655 -5.186"></path>', keywords: ['prism', '3d', 'optics', 'light', 'geometric'], category: 'Abstract' },
  { name: 'Hexagons', lucide: '', svg: '<path d="M4 18v-5l4 -2l4 2v5l-4 2z"></path><path d="M8 11v-5l4 -2l4 2v5"></path><path d="M12 13l4 -2l4 2v5l-4 2l-4 -2"></path>', keywords: ['hexagons', 'honeycomb', 'pattern', 'tile', 'tessellate'], category: 'Abstract' },
  { name: 'YinYang', lucide: '', svg: '<path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path><path d="M12 3a4.5 4.5 0 0 0 0 9a4.5 4.5 0 0 1 0 9"></path><circle cx="12" cy="7.5" r=".5" fill="currentColor"></circle><circle cx="12" cy="16.5" r=".5" fill="currentColor"></circle>', keywords: ['yin yang', 'balance', 'duality', 'harmony', 'circle'], category: 'Abstract' },
  { name: 'Polygon', lucide: '', svg: '<path d="M12 5m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M19 8m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M5 11m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M15 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M6.5 9.5l3.5 -3"></path><path d="M14 5.5l3 1.5"></path><path d="M18.5 10l-2.5 7"></path><path d="M13.5 17.5l-7 -5"></path>', keywords: ['polygon', 'shape', 'vector', 'multi-sided', 'geometric'], category: 'Abstract' },
  { name: 'VectorPath', lucide: '', svg: '<path d="M3 3m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M17 3m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M17 17m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M3 17m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M5 7l0 10"></path><path d="M19 7l0 10"></path><path d="M7 5l10 0"></path><path d="M7 19l10 0"></path>', keywords: ['vector', 'path', 'anchor', 'points', 'design'], category: 'Abstract' },
  { name: 'VectorBezier', lucide: '', svg: '<path d="M3 14m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M17 14m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M10 6m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M10 8.5a6 6 0 0 0 -5 5.5"></path><path d="M14 8.5a6 6 0 0 1 5 5.5"></path><path d="M10 8l-6 0"></path><path d="M20 8l-6 0"></path><path d="M3 8m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path><path d="M21 8m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>', keywords: ['bezier', 'curve', 'path', 'vector', 'smooth handle'], category: 'Abstract' },
  { name: 'VectorBezier2', lucide: '', svg: '<path d="M3 3m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M17 17m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M7 5l7 0"></path><path d="M10 19l7 0"></path><path d="M9 19m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path><path d="M15 5m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path><path d="M7 5.5a5 6.5 0 0 1 5 6.5a5 6.5 0 0 0 5 6.5"></path>', keywords: ['bezier', 'curve', 'control point', 'path', 'handle'], category: 'Abstract' },
  { name: 'VectorSpline', lucide: '', svg: '<path d="M17 3m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M3 17m0 1a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"></path><path d="M17 5c-6.627 0 -12 5.373 -12 12"></path>', keywords: ['spline', 'curve', 'smooth', 'path', 'bezier arc'], category: 'Abstract' },
  { name: 'Transform', lucide: '', svg: '<path d="M3 6a3 3 0 1 0 6 0a3 3 0 0 0 -6 0"></path><path d="M21 11v-3a2 2 0 0 0 -2 -2h-6l3 3m0 -6l-3 3"></path><path d="M3 13v3a2 2 0 0 0 2 2h6l-3 -3m0 6l3 -3"></path><path d="M15 18a3 3 0 1 0 6 0a3 3 0 0 0 -6 0"></path>', keywords: ['transform', 'scale', 'rotate', 'modify', 'warp'], category: 'Abstract' },
  { name: 'Perspective', lucide: '', svg: '<path d="M6.141 4.163l12 1.714a1 1 0 0 1 .859 .99v10.266a1 1 0 0 1 -.859 .99l-12 1.714a1 1 0 0 1 -1.141 -.99v-13.694a1 1 0 0 1 1.141 -.99z"></path>', keywords: ['perspective', 'vanishing point', '3d', 'depth', 'foreshorten'], category: 'Abstract' },
  { name: 'Geometry', lucide: '', svg: '<path d="M7 21l4 -12m2 0l1.48 4.439m.949 2.847l1.571 4.714"></path><path d="M12 7m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M4 12c1.526 2.955 4.588 5 8 5c3.41 0 6.473 -2.048 8 -5"></path><path d="M12 5v-2"></path>', keywords: ['geometry', 'shapes', 'math', 'figure', 'diagram'], category: 'Abstract' },
  { name: 'Circles', lucide: '', svg: '<path d="M12 7m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path><path d="M6.5 17m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path><path d="M17.5 17m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>', keywords: ['circles', 'multiple', 'rings', 'overlap', 'bubbles'], category: 'Abstract' },
  { name: 'TopologyComplex', lucide: '', svg: '<path d="M20 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M8 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M8 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M20 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M14 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M7.5 7.5l3 3"></path><path d="M6 8v8"></path><path d="M18 16v-8"></path><path d="M8 6h8"></path><path d="M16 18h-8"></path>', keywords: ['topology', 'network', 'nodes', 'complex', 'graph structure'], category: 'Abstract' },
  { name: 'TopologyRing', lucide: '', svg: '<path d="M14 20a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M14 4a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M6 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M22 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M13.5 5.5l5 5"></path><path d="M5.5 13.5l5 5"></path><path d="M13.5 18.5l5 -5"></path><path d="M10.5 5.5l-5 5"></path>', keywords: ['topology', 'ring', 'network', 'circular', 'loop network'], category: 'Abstract' },
  { name: 'TopologyStar', lucide: '', svg: '<path d="M8 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M20 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M8 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M20 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M14 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M7.5 7.5l3 3"></path><path d="M7.5 16.5l3 -3"></path><path d="M13.5 13.5l3 3"></path><path d="M16.5 7.5l-3 3"></path>', keywords: ['topology', 'star', 'hub', 'central', 'network'], category: 'Abstract' },
  { name: 'TopologyFull', lucide: '', svg: '<path d="M20 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M8 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M8 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M20 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0z"></path><path d="M6 8v8"></path><path d="M18 16v-8"></path><path d="M8 6h8"></path><path d="M16 18h-8"></path><path d="M7.5 7.5l9 9"></path><path d="M7.5 16.5l9 -9"></path>', keywords: ['topology', 'full mesh', 'all connected', 'network', 'graph'], category: 'Abstract' },

  // ── Business ──────────────────────────────────────────────────────────────────
  { name: 'Briefcase', lucide: 'Briefcase', keywords: ['work', 'job', 'business', 'career', 'office'], category: 'Business' },
  { name: 'Building', lucide: 'Building', keywords: ['office', 'company', 'corporate', 'building', 'architecture'], category: 'Business' },
  { name: 'Building2', lucide: 'Building2', keywords: ['skyscraper', 'office', 'company', 'city', 'enterprise'], category: 'Business' },
  { name: 'BarChart', lucide: 'BarChart', keywords: ['analytics', 'stats', 'chart', 'data', 'metrics'], category: 'Business' },
  { name: 'BarChart2', lucide: 'BarChart2', keywords: ['analytics', 'stats', 'bar', 'data', 'report'], category: 'Business' },
  { name: 'PieChart', lucide: 'PieChart', keywords: ['pie', 'chart', 'analytics', 'data', 'share'], category: 'Business' },
  { name: 'AreaChart', lucide: 'AreaChart', keywords: ['area', 'chart', 'analytics', 'trend', 'data'], category: 'Business' },
  { name: 'TrendingUp', lucide: 'TrendingUp', keywords: ['growth', 'increase', 'trend', 'analytics', 'improvement'], category: 'Business' },
  { name: 'TrendingDown', lucide: 'TrendingDown', keywords: ['decline', 'decrease', 'trend', 'analytics', 'loss'], category: 'Business' },
  { name: 'Handshake', lucide: 'Handshake', keywords: ['deal', 'partnership', 'agreement', 'collaboration', 'hire'], category: 'Business' },
  { name: 'Award', lucide: 'Award', keywords: ['award', 'achievement', 'prize', 'recognition', 'badge'], category: 'Business' },
  { name: 'Crown', lucide: 'Crown', keywords: ['premium', 'king', 'royal', 'top', 'best', 'leader'], category: 'Business' },
  { name: 'Presentation', lucide: 'Presentation', keywords: ['presentation', 'slides', 'meeting', 'pitch', 'demo'], category: 'Business' },
  { name: 'ClipboardList', lucide: 'ClipboardList', keywords: ['list', 'tasks', 'checklist', 'todo', 'resume'], category: 'Business' },
  { name: 'ClipboardCheck', lucide: 'ClipboardCheck', keywords: ['done', 'approved', 'checklist', 'complete', 'task'], category: 'Business' },
  { name: 'FileText', lucide: 'FileText', keywords: ['document', 'file', 'report', 'contract', 'resume'], category: 'Business' },
  { name: 'FileCheck', lucide: 'FileCheck', keywords: ['approved', 'document', 'signed', 'verified', 'complete'], category: 'Business' },
  { name: 'Megaphone', lucide: 'Megaphone', keywords: ['announce', 'marketing', 'promote', 'ads', 'campaign'], category: 'Business' },
  { name: 'Blocks', lucide: 'Blocks', keywords: ['blocks', 'modular', 'components', 'build', 'modules'], category: 'Business' },
  { name: 'Scale', lucide: 'Scale', keywords: ['legal', 'law', 'balance', 'justice', 'compliance'], category: 'Business' },
  { name: 'Landmark', lucide: 'Landmark', keywords: ['bank', 'government', 'institution', 'legal', 'civic'], category: 'Business' },

  // ── People ────────────────────────────────────────────────────────────────────
  { name: 'User', lucide: 'User', keywords: ['person', 'profile', 'account', 'user', 'individual'], category: 'People' },
  { name: 'UserRound', lucide: 'UserRound', keywords: ['person', 'profile', 'account', 'user', 'avatar'], category: 'People' },
  { name: 'Users', lucide: 'Users', keywords: ['team', 'group', 'people', 'community', 'users', 'staff'], category: 'People' },
  { name: 'Users2', lucide: 'Users2', keywords: ['team', 'pair', 'duo', 'people', 'together'], category: 'People' },
  { name: 'UserCheck', lucide: 'UserCheck', keywords: ['verified', 'hired', 'approved', 'accepted', 'confirmed'], category: 'People' },
  { name: 'UserPlus', lucide: 'UserPlus', keywords: ['add user', 'invite', 'new member', 'register', 'recruit'], category: 'People' },
  { name: 'UserSearch', lucide: 'UserSearch', keywords: ['find', 'search', 'candidate', 'recruit', 'hire', 'talent'], category: 'People' },
  { name: 'UserCog', lucide: 'UserCog', keywords: ['admin', 'manage', 'user settings', 'profile', 'configure'], category: 'People' },
  { name: 'UserRoundCheck', lucide: 'UserRoundCheck', keywords: ['verified', 'approved', 'confirmed', 'user', 'round'], category: 'People' },
  { name: 'UsersRound', lucide: 'UsersRound', keywords: ['team', 'group', 'community', 'users', 'round', 'circle'], category: 'People' },
  { name: 'HeartHandshake', lucide: 'HeartHandshake', keywords: ['care', 'support', 'help', 'trust', 'volunteer', 'community'], category: 'People' },
  { name: 'PersonStanding', lucide: 'PersonStanding', keywords: ['person', 'human', 'individual', 'employee', 'worker'], category: 'People' },
  { name: 'Contact', lucide: 'Contact', keywords: ['contact', 'profile', 'card', 'id', 'identity'], category: 'People' },
  { name: 'Baby', lucide: 'Baby', keywords: ['baby', 'child', 'kid', 'infant', 'family', 'parenting'], category: 'People' },
  { name: 'Smile', lucide: 'Smile', keywords: ['smile', 'happy', 'emoji', 'face', 'positive', 'friendly'], category: 'People' },

  // ── Remote Work ───────────────────────────────────────────────────────────────
  { name: 'Headset', lucide: 'Headset', keywords: ['headset', 'support', 'call', 'remote', 'audio', 'customer service'], category: 'Remote Work' },
  { name: 'VideoOff', lucide: 'VideoOff', keywords: ['muted', 'video off', 'camera off', 'remote', 'meeting'], category: 'Remote Work' },
  { name: 'MonitorCheck', lucide: 'MonitorCheck', keywords: ['remote', 'screen', 'verified', 'setup', 'desktop', 'work'], category: 'Remote Work' },
  { name: 'MonitorDot', lucide: 'MonitorDot', keywords: ['online', 'active', 'remote', 'status', 'connected', 'screen'], category: 'Remote Work' },
  { name: 'MonitorSmartphone', lucide: 'MonitorSmartphone', keywords: ['cross-device', 'remote', 'flexible', 'mobile work', 'responsive'], category: 'Remote Work' },
  { name: 'Globe2', lucide: 'Globe2', keywords: ['global', 'remote', 'distributed', 'international', 'world', 'anywhere'], category: 'Remote Work' },
  { name: 'CalendarClock', lucide: 'CalendarClock', keywords: ['schedule', 'meeting', 'remote', 'timezone', 'time', 'call'], category: 'Remote Work' },
  { name: 'Wifi', lucide: 'Wifi', keywords: ['wifi', 'internet', 'remote', 'connected', 'online', 'network'], category: 'Remote Work' },
  { name: 'WifiOff', lucide: 'WifiOff', keywords: ['wifi off', 'disconnected', 'no internet', 'remote', 'offline'], category: 'Remote Work' },
  { name: 'Laptop', lucide: 'Laptop', keywords: ['laptop', 'remote', 'wfh', 'work', 'computer', 'mobile work'], category: 'Remote Work' },
  { name: 'CloudUpload', lucide: 'CloudUpload', keywords: ['cloud', 'sync', 'remote', 'upload', 'collaborate', 'share'], category: 'Remote Work' },
  { name: 'CloudDownload', lucide: 'CloudDownload', keywords: ['cloud', 'download', 'remote', 'access', 'sync', 'files'], category: 'Remote Work' },
  { name: 'CloudCog', lucide: 'CloudCog', keywords: ['cloud', 'settings', 'remote', 'configure', 'setup', 'devops'], category: 'Remote Work' },
  { name: 'MessagesSquare', lucide: 'MessagesSquare', keywords: ['async', 'chat', 'remote', 'team', 'slack', 'communication'], category: 'Remote Work' },
  { name: 'Satellite', lucide: 'Satellite', keywords: ['satellite', 'remote', 'signal', 'far', 'connected', 'global'], category: 'Remote Work' },
  { name: 'BriefcaseBusiness', lucide: 'BriefcaseBusiness', keywords: ['job', 'work', 'career', 'business', 'professional', 'employment'], category: 'Remote Work' },
  { name: 'ScreenShare', lucide: 'ScreenShare', keywords: ['screen share', 'present', 'remote', 'meeting', 'zoom', 'collaborate'], category: 'Remote Work' },
  { name: 'ScreenShareOff', lucide: 'ScreenShareOff', keywords: ['screen share off', 'stop share', 'remote', 'meeting', 'end'], category: 'Remote Work' },
  { name: 'Cast', lucide: 'Cast', keywords: ['cast', 'stream', 'mirror', 'remote', 'screen', 'tv'], category: 'Remote Work' },
  { name: 'Projector', lucide: 'Projector', keywords: ['projector', 'present', 'meeting', 'remote', 'display', 'demo'], category: 'Remote Work' },
  { name: 'GanttChart', lucide: 'GanttChart', keywords: ['gantt', 'project', 'timeline', 'remote', 'planning', 'schedule'], category: 'Remote Work' },
  { name: 'CheckCheck', lucide: 'CheckCheck', keywords: ['done', 'complete', 'delivered', 'remote', 'task', 'double check'], category: 'Remote Work' },
  { name: 'NotepadText', lucide: 'NotepadText', keywords: ['notes', 'meeting notes', 'remote', 'notepad', 'text', 'write'], category: 'Remote Work' },
  { name: 'NotebookPen', lucide: 'NotebookPen', keywords: ['notebook', 'pen', 'remote', 'write', 'journal', 'notes'], category: 'Remote Work' },
  { name: 'Cable', lucide: 'Cable', keywords: ['cable', 'connection', 'wire', 'ethernet', 'usb', 'plug'], category: 'Remote Work' },
  { name: 'FileCode', lucide: 'FileCode', keywords: ['code', 'file', 'remote', 'developer', 'script', 'program'], category: 'Remote Work' },
  { name: 'FileCode2', lucide: 'FileCode2', keywords: ['code', 'file', 'script', 'remote', 'developer', 'brackets'], category: 'Remote Work' },
  { name: 'MicOff', lucide: 'MicOff', keywords: ['mute', 'mic off', 'remote', 'call', 'silent', 'meeting'], category: 'Remote Work' },
  { name: 'CameraOff', lucide: 'CameraOff', keywords: ['camera off', 'video off', 'remote', 'meeting', 'mute camera'], category: 'Remote Work' },
  { name: 'FolderSync', lucide: 'FolderSync', keywords: ['folder', 'sync', 'remote', 'cloud', 'backup', 'files'], category: 'Remote Work' },
  { name: 'PlugZap', lucide: 'PlugZap', keywords: ['plug', 'power', 'connect', 'charge', 'remote', 'energy'], category: 'Remote Work' },
  { name: 'TimerOff', lucide: 'TimerOff', keywords: ['timer off', 'pause', 'break', 'remote', 'stop', 'rest'], category: 'Remote Work' },
  { name: 'ClipboardPen', lucide: 'ClipboardPen', keywords: ['clipboard', 'pen', 'write', 'remote', 'notes', 'task'], category: 'Remote Work' },
  // More Lucide remote work icons
  { name: 'HardDriveUpload', lucide: 'HardDriveUpload', keywords: ['upload', 'backup', 'drive', 'remote', 'save', 'store'], category: 'Remote Work' },
  { name: 'HardDriveDownload', lucide: 'HardDriveDownload', keywords: ['download', 'restore', 'drive', 'remote', 'fetch', 'sync'], category: 'Remote Work' },
  { name: 'FileSpreadsheet', lucide: 'FileSpreadsheet', keywords: ['spreadsheet', 'excel', 'data', 'remote', 'file', 'table'], category: 'Remote Work' },
  { name: 'FolderKanban', lucide: 'FolderKanban', keywords: ['folder', 'kanban', 'project', 'remote', 'organize', 'board'], category: 'Remote Work' },
  { name: 'FolderGit2', lucide: 'FolderGit2', keywords: ['git', 'folder', 'repository', 'remote', 'version control', 'dev'], category: 'Remote Work' },
  { name: 'FolderOutput', lucide: 'FolderOutput', keywords: ['folder', 'output', 'export', 'remote', 'share', 'release'], category: 'Remote Work' },
  { name: 'Files', lucide: 'Files', keywords: ['files', 'documents', 'multiple', 'remote', 'work', 'collection'], category: 'Remote Work' },
  { name: 'MonitorOff', lucide: 'MonitorOff', keywords: ['monitor off', 'sleep', 'end session', 'remote', 'break', 'done'], category: 'Remote Work' },
  { name: 'LaptopMinimal', lucide: 'LaptopMinimal', keywords: ['laptop', 'minimal', 'wfh', 'remote', 'work', 'portable'], category: 'Remote Work' },
  { name: 'CloudOff', lucide: 'CloudOff', keywords: ['cloud off', 'offline', 'no cloud', 'remote', 'disconnected'], category: 'Remote Work' },
  { name: 'KanbanSquare', lucide: 'KanbanSquare', keywords: ['kanban', 'board', 'task', 'remote', 'agile', 'sprint'], category: 'Remote Work' },
  { name: 'BookUser', lucide: 'BookUser', keywords: ['address book', 'contacts', 'team', 'remote', 'directory', 'people'], category: 'Remote Work' },
  { name: 'ClipboardCopy', lucide: 'ClipboardCopy', keywords: ['clipboard', 'copy', 'remote', 'share', 'duplicate', 'task'], category: 'Remote Work' },
  { name: 'SquarePen', lucide: 'SquarePen', keywords: ['edit', 'pen', 'write', 'remote', 'task', 'create'], category: 'Remote Work' },
  // Custom SVG icons — unique remote work concepts
  {
    name: 'VPN',
    lucide: '',
    svg: '<path d="M12 2L4 6V12C4 16.4 7.4 20.7 12 22C16.6 20.7 20 16.4 20 12V6L12 2Z"/><circle cx="12" cy="11" r="2"/><line x1="12" y1="13" x2="12" y2="16"/>',
    keywords: ['vpn', 'secure', 'tunnel', 'private', 'network', 'remote', 'shield', 'lock'],
    category: 'Remote Work'
  },
  {
    name: 'WorldClock',
    lucide: '',
    svg: '<circle cx="12" cy="12" r="10"/><path d="M12 2C10 7 10 17 12 22"/><path d="M12 2C14 7 14 17 12 22"/><line x1="2" y1="12" x2="22" y2="12"/><line x1="12" y1="6" x2="16" y2="9"/>',
    keywords: ['timezone', 'world', 'clock', 'global', 'remote', 'international', 'time'],
    category: 'Remote Work'
  },

  // ── Remote Work: Tabler Icons (react-icons/tb) — 24x24 stroke, same style as Lucide ──
  { name: 'HomeSignal', lucide: '', svg: '<path d="M15 22v-2"></path><path d="M18 22v-4"></path><path d="M21 22v-6"></path><path d="M19 12.494v-.494h2l-9 -9l-9 9h2v7a2 2 0 0 0 2 2h4"></path><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v.5"></path>', keywords: ['home', 'signal', 'remote', 'wfh', 'connected', 'bars'], category: 'Remote Work' },
  { name: 'HomeCheck', lucide: '', svg: '<path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2"></path><path d="M19 13.488v-1.488h2l-9 -9l-9 9h2v7a2 2 0 0 0 2 2h4.525"></path><path d="M15 19l2 2l4 -4"></path>', keywords: ['home', 'verified', 'wfh', 'remote', 'approved', 'done'], category: 'Remote Work' },
  { name: 'Timezone', lucide: '', svg: '<path d="M20.884 10.554a9 9 0 1 0 -10.337 10.328"></path><path d="M3.6 9h16.8"></path><path d="M3.6 15h6.9"></path><path d="M11.5 3a17 17 0 0 0 -1.502 14.954"></path><path d="M12.5 3a17 17 0 0 1 2.52 7.603"></path><path d="M18 18m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path><path d="M18 16.5v1.5l.5 .5"></path>', keywords: ['timezone', 'world clock', 'remote', 'global', 'time zone'], category: 'Remote Work' },
  { name: 'ClockPlay', lucide: '', svg: '<path d="M12 7v5l2 2"></path><path d="M17 22l5 -3l-5 -3z"></path><path d="M13.017 20.943a9 9 0 1 1 7.831 -7.292"></path>', keywords: ['start', 'timer', 'begin work', 'track time', 'clock'], category: 'Remote Work' },
  { name: 'ClockPause', lucide: '', svg: '<path d="M20.942 13.018a9 9 0 1 0 -7.909 7.922"></path><path d="M12 7v5l2 2"></path><path d="M17 17v5"></path><path d="M21 17v5"></path>', keywords: ['pause', 'break', 'rest', 'timer', 'clock'], category: 'Remote Work' },
  { name: 'ClockCheck', lucide: '', svg: '<path d="M20.942 13.021a9 9 0 1 0 -9.407 7.967"></path><path d="M12 7v5l3 3"></path><path d="M15 19l2 2l4 -4"></path>', keywords: ['done', 'deadline', 'finished', 'clock', 'time'], category: 'Remote Work' },
  { name: 'ClockStop', lucide: '', svg: '<path d="M21 12a9 9 0 1 0 -9 9"></path><path d="M12 7v5l1 1"></path><path d="M16 16h6v6h-6z"></path>', keywords: ['stop', 'end work', 'timer', 'clock', 'finish'], category: 'Remote Work' },
  { name: 'ClockRecord', lucide: '', svg: '<path d="M21 12.3a9 9 0 1 0 -8.683 8.694"></path><path d="M12 7v5l2 2"></path><path d="M19 19m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>', keywords: ['record', 'time track', 'log', 'clock', 'working hours'], category: 'Remote Work' },
  { name: 'UsersGroup', lucide: '', svg: '<path d="M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path><path d="M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1"></path><path d="M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path><path d="M17 10h2a2 2 0 0 1 2 2v1"></path><path d="M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path><path d="M3 13v-1a2 2 0 0 1 2 -2h2"></path>', keywords: ['team', 'group', 'squad', 'distributed', 'remote team'], category: 'Remote Work' },
  { name: 'DesktopCode', lucide: '', svg: '<path d="M12.5 16h-8.5a1 1 0 0 1 -1 -1v-10a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v8"></path><path d="M7 20h4"></path><path d="M9 16v4"></path><path d="M20 21l2 -2l-2 -2"></path><path d="M17 17l-2 2l2 2"></path>', keywords: ['desktop', 'code', 'dev setup', 'remote', 'development'], category: 'Remote Work' },
  { name: 'DesktopShare', lucide: '', svg: '<path d="M12.5 16h-8.5a1 1 0 0 1 -1 -1v-10a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v8"></path><path d="M7 20h5.5"></path><path d="M9 16v4"></path><path d="M16 22l5 -5"></path><path d="M21 21.5v-4.5h-4.5"></path>', keywords: ['screen share', 'desktop', 'present', 'remote', 'mirror'], category: 'Remote Work' },
  { name: 'DesktopAnalytics', lucide: '', svg: '<path d="M3 4m0 1a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1z"></path><path d="M7 20h10"></path><path d="M9 16v4"></path><path d="M15 16v4"></path><path d="M9 12v-4"></path><path d="M12 12v-1"></path><path d="M15 12v-2"></path><path d="M12 12v-1"></path>', keywords: ['analytics', 'dashboard', 'desktop', 'metrics', 'remote'], category: 'Remote Work' },
  { name: 'Webhook', lucide: '', svg: '<path d="M4.876 13.61a4 4 0 1 0 6.124 3.39h6"></path><path d="M15.066 20.502a4 4 0 1 0 1.934 -7.502c-.706 0 -1.424 .179 -2 .5l-3 -5.5"></path><path d="M16 8a4 4 0 1 0 -8 0c0 1.506 .77 2.818 2 3.5l-3 5.5"></path>', keywords: ['webhook', 'api', 'trigger', 'integration', 'automation'], category: 'Remote Work' },
  { name: 'PresentationAnalytics', lucide: '', svg: '<path d="M9 12v-4"></path><path d="M15 12v-2"></path><path d="M12 12v-1"></path><path d="M3 4h18"></path><path d="M4 4v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-10"></path><path d="M12 16v4"></path><path d="M9 20h6"></path>', keywords: ['analytics', 'present', 'data', 'remote', 'report'], category: 'Remote Work' },
  { name: 'ClipboardData', lucide: '', svg: '<path d="M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2"></path><path d="M9 3m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v0a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path><path d="M9 17v-4"></path><path d="M12 17v-1"></path><path d="M15 17v-2"></path><path d="M12 17v-1"></path>', keywords: ['clipboard', 'data', 'report', 'remote', 'metrics', 'notes'], category: 'Remote Work' },
  { name: 'ReportAnalytics', lucide: '', svg: '<path d="M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2"></path><path d="M9 3m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v0a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path><path d="M9 17v-5"></path><path d="M12 17v-1"></path><path d="M15 17v-3"></path>', keywords: ['report', 'analytics', 'remote', 'data', 'chart'], category: 'Remote Work' },
  { name: 'CalendarEvent', lucide: '', svg: '<path d="M4 5m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M16 3l0 4"></path><path d="M8 3l0 4"></path><path d="M4 11l16 0"></path><path d="M8 15h2v2h-2z"></path>', keywords: ['event', 'meeting', 'calendar', 'remote', 'schedule'], category: 'Remote Work' },
  { name: 'VideoMeet', lucide: '', svg: '<path d="M17.011 9.385v5.128l3.989 3.487v-12z"></path><path d="M3.887 6h10.08c1.468 0 3.033 1.203 3.033 2.803v8.196a.991 .991 0 0 1 -.975 1h-10.373c-1.667 0 -2.652 -1.5 -2.652 -3l.01 -8a.882 .882 0 0 1 .208 -.71a.841 .841 0 0 1 .67 -.287z"></path>', keywords: ['video', 'meeting', 'zoom', 'conference', 'remote call'], category: 'Remote Work' },
  { name: 'TeamChat', lucide: '', svg: '<path d="M12 12v-6a2 2 0 0 1 4 0v6m0 -2a2 2 0 1 1 2 2h-6"></path><path d="M12 12h6a2 2 0 0 1 0 4h-6m2 0a2 2 0 1 1 -2 2v-6"></path><path d="M12 12v6a2 2 0 0 1 -4 0v-6m0 2a2 2 0 1 1 -2 -2h6"></path><path d="M12 12h-6a2 2 0 0 1 0 -4h6m-2 0a2 2 0 1 1 2 -2v6"></path>', keywords: ['chat', 'slack', 'team', 'async', 'remote', 'message'], category: 'Remote Work' },
  { name: 'CodeRepo', lucide: '', svg: '<path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path>', keywords: ['git', 'repo', 'code', 'remote', 'developer', 'version'], category: 'Remote Work' },

  // ── Help & Support ────────────────────────────────────────────────────────────
  { name: 'CircleHelp', lucide: 'CircleHelp', keywords: ['help', 'question', 'faq', 'support', 'info', 'guide'], category: 'Help & Support' },
  { name: 'HelpCircle', lucide: 'HelpCircle', keywords: ['help', 'question', 'faq', 'info', 'support', 'assist'], category: 'Help & Support' },
  { name: 'LifeBuoy', lucide: 'LifeBuoy', keywords: ['support', 'help', 'rescue', 'sos', 'customer service', 'care'], category: 'Help & Support' },
  { name: 'Info', lucide: 'Info', keywords: ['info', 'information', 'detail', 'about', 'tip', 'note'], category: 'Help & Support' },
  { name: 'MessageCircleQuestion', lucide: 'MessageCircleQuestion', keywords: ['question', 'ask', 'support', 'help', 'chat', 'faq'], category: 'Help & Support' },
  { name: 'BadgeHelp', lucide: 'BadgeHelp', keywords: ['help', 'badge', 'support', 'faq', 'guide', 'question'], category: 'Help & Support' },
  { name: 'Signpost', lucide: 'Signpost', keywords: ['guide', 'direction', 'wayfinding', 'signpost', 'onboarding', 'path'], category: 'Help & Support' },
  { name: 'SignpostBig', lucide: 'SignpostBig', keywords: ['guide', 'signpost', 'directions', 'help', 'navigate', 'tutorial'], category: 'Help & Support' },
  { name: 'BookOpenCheck', lucide: 'BookOpenCheck', keywords: ['guide', 'tutorial', 'documentation', 'learn', 'instructions', 'manual'], category: 'Help & Support' },
  { name: 'Lightbulb', lucide: 'Lightbulb', keywords: ['tip', 'idea', 'guide', 'insight', 'help', 'hint', 'suggestion'], category: 'Help & Support' },
  { name: 'ListOrdered', lucide: 'ListOrdered', keywords: ['steps', 'guide', 'instructions', 'tutorial', 'numbered', 'howto'], category: 'Help & Support' },
  { name: 'Route', lucide: 'Route', keywords: ['path', 'guide', 'steps', 'journey', 'tutorial', 'onboarding'], category: 'Help & Support' },
  { name: 'Waypoints', lucide: 'Waypoints', keywords: ['steps', 'guide', 'journey', 'milestones', 'path', 'tutorial'], category: 'Help & Support' },
  { name: 'Milestone', lucide: 'Milestone', keywords: ['milestone', 'progress', 'guide', 'goal', 'checkpoint', 'stage'], category: 'Help & Support' },
  { name: 'HandHeart', lucide: 'HandHeart', keywords: ['care', 'help', 'give', 'support', 'volunteer', 'community'], category: 'Help & Support' },
  { name: 'Accessibility', lucide: 'Accessibility', keywords: ['accessibility', 'inclusive', 'help', 'support', 'a11y', 'guide'], category: 'Help & Support' },
  { name: 'ScrollText', lucide: 'ScrollText', keywords: ['guide', 'manual', 'documentation', 'tutorial', 'instructions', 'scroll'], category: 'Help & Support' },
  { name: 'FileQuestion', lucide: 'FileQuestion', keywords: ['faq', 'help', 'question', 'support', 'document', 'unknown'], category: 'Help & Support' },

  // ── Technology ────────────────────────────────────────────────────────────────
  { name: 'Code', lucide: 'Code', keywords: ['code', 'developer', 'programming', 'tech', 'software', 'dev'], category: 'Technology' },
  { name: 'Code2', lucide: 'Code2', keywords: ['code', 'developer', 'programming', 'brackets', 'syntax'], category: 'Technology' },
  { name: 'Cpu', lucide: 'Cpu', keywords: ['cpu', 'processor', 'hardware', 'tech', 'chip', 'compute'], category: 'Technology' },
  { name: 'CircuitBoard', lucide: 'CircuitBoard', keywords: ['circuit', 'hardware', 'electronics', 'chip', 'pcb', 'tech'], category: 'Technology' },
  { name: 'Database', lucide: 'Database', keywords: ['database', 'storage', 'data', 'server', 'backend', 'sql'], category: 'Technology' },
  { name: 'Server', lucide: 'Server', keywords: ['server', 'hosting', 'backend', 'infrastructure', 'cloud'], category: 'Technology' },
  { name: 'HardDrive', lucide: 'HardDrive', keywords: ['storage', 'disk', 'hard drive', 'hdd', 'data', 'backup'], category: 'Technology' },
  { name: 'Cloud', lucide: 'Cloud', keywords: ['cloud', 'hosting', 'storage', 'saas', 'online', 'aws'], category: 'Technology' },
  { name: 'Smartphone', lucide: 'Smartphone', keywords: ['phone', 'mobile', 'app', 'device', 'ios', 'android'], category: 'Technology' },
  { name: 'Tablet', lucide: 'Tablet', keywords: ['tablet', 'ipad', 'device', 'mobile', 'app'], category: 'Technology' },
  { name: 'Monitor', lucide: 'Monitor', keywords: ['screen', 'desktop', 'display', 'computer', 'web'], category: 'Technology' },
  { name: 'Keyboard', lucide: 'Keyboard', keywords: ['keyboard', 'type', 'input', 'hardware', 'computer'], category: 'Technology' },
  { name: 'Mouse', lucide: 'Mouse', keywords: ['mouse', 'cursor', 'click', 'hardware', 'peripheral'], category: 'Technology' },
  { name: 'Printer', lucide: 'Printer', keywords: ['print', 'printer', 'document', 'office', 'paper'], category: 'Technology' },
  { name: 'Router', lucide: 'Router', keywords: ['router', 'network', 'internet', 'wifi', 'connection'], category: 'Technology' },
  { name: 'Terminal', lucide: 'Terminal', keywords: ['terminal', 'console', 'command', 'developer', 'cli'], category: 'Technology' },
  { name: 'AppWindow', lucide: 'AppWindow', keywords: ['app', 'window', 'browser', 'ui', 'desktop', 'software'], category: 'Technology' },
  { name: 'Bot', lucide: 'Bot', keywords: ['bot', 'ai', 'robot', 'automation', 'artificial intelligence'], category: 'Technology' },
  { name: 'BrainCircuit', lucide: 'BrainCircuit', keywords: ['ai', 'machine learning', 'brain', 'intelligence', 'neural'], category: 'Technology' },
  { name: 'Bluetooth', lucide: 'Bluetooth', keywords: ['bluetooth', 'wireless', 'connect', 'pairing', 'device'], category: 'Technology' },
  { name: 'Antenna', lucide: 'Antenna', keywords: ['antenna', 'signal', 'broadcast', 'radio', 'wireless'], category: 'Technology' },
  { name: 'GitBranch', lucide: 'GitBranch', keywords: ['git', 'version', 'branch', 'code', 'developer', 'repository'], category: 'Technology' },
  { name: 'GitMerge', lucide: 'GitMerge', keywords: ['git', 'merge', 'combine', 'branch', 'code', 'repository'], category: 'Technology' },
  { name: 'Container', lucide: 'Container', keywords: ['docker', 'container', 'deploy', 'devops', 'microservice'], category: 'Technology' },
  { name: 'QrCode', lucide: 'QrCode', keywords: ['qr', 'code', 'scan', 'barcode', 'link', 'mobile'], category: 'Technology' },
  { name: 'Plug', lucide: 'Plug', keywords: ['plug', 'connect', 'power', 'api', 'integration', 'plugin'], category: 'Technology' },

  // ── Location ──────────────────────────────────────────────────────────────────
  { name: 'MapPin', lucide: 'MapPin', keywords: ['location', 'place', 'map', 'pin', 'marker', 'address', 'gps'], category: 'Location' },
  { name: 'MapPinOff', lucide: 'MapPinOff', keywords: ['location off', 'no gps', 'unpin', 'remove', 'missing'], category: 'Location' },
  { name: 'Map', lucide: 'Map', keywords: ['map', 'navigate', 'route', 'geography', 'area'], category: 'Location' },
  { name: 'Globe', lucide: 'Globe', keywords: ['global', 'world', 'international', 'planet', 'web', 'online'], category: 'Location' },
  { name: 'Navigation', lucide: 'Navigation', keywords: ['navigate', 'direction', 'gps', 'compass', 'route'], category: 'Location' },
  { name: 'Compass', lucide: 'Compass', keywords: ['compass', 'direction', 'navigation', 'explore', 'orient'], category: 'Location' },
  { name: 'Locate', lucide: 'Locate', keywords: ['locate', 'find', 'gps', 'target', 'position', 'spot'], category: 'Location' },
  { name: 'MountainSnow', lucide: 'MountainSnow', keywords: ['mountain', 'snow', 'peak', 'landscape', 'winter', 'hike'], category: 'Location' },
  { name: 'Factory', lucide: 'Factory', keywords: ['factory', 'industrial', 'manufacturing', 'plant', 'production'], category: 'Location' },

  // ── Communication ─────────────────────────────────────────────────────────────
  { name: 'Mail', lucide: 'Mail', keywords: ['email', 'mail', 'message', 'inbox', 'contact', 'letter'], category: 'Communication' },
  { name: 'MailOpen', lucide: 'MailOpen', keywords: ['email', 'open', 'read', 'inbox', 'message'], category: 'Communication' },
  { name: 'Inbox', lucide: 'Inbox', keywords: ['inbox', 'email', 'messages', 'receive', 'mail', 'tray'], category: 'Communication' },
  { name: 'MessageCircle', lucide: 'MessageCircle', keywords: ['chat', 'message', 'conversation', 'comment', 'talk'], category: 'Communication' },
  { name: 'MessageSquare', lucide: 'MessageSquare', keywords: ['message', 'chat', 'comment', 'feedback', 'support'], category: 'Communication' },
  { name: 'Bell', lucide: 'Bell', keywords: ['notification', 'alert', 'bell', 'reminder', 'notify'], category: 'Communication' },
  { name: 'BellRing', lucide: 'BellRing', keywords: ['alarm', 'ring', 'alert', 'notify', 'urgent'], category: 'Communication' },
  { name: 'Phone', lucide: 'Phone', keywords: ['phone', 'call', 'contact', 'telephone', 'voice'], category: 'Communication' },
  { name: 'PhoneCall', lucide: 'PhoneCall', keywords: ['call', 'phone', 'ringing', 'voice', 'contact'], category: 'Communication' },
  { name: 'PhoneIncoming', lucide: 'PhoneIncoming', keywords: ['incoming', 'call', 'receive', 'phone', 'answer'], category: 'Communication' },
  { name: 'Send', lucide: 'Send', keywords: ['send', 'submit', 'share', 'email', 'message', 'deliver'], category: 'Communication' },
  { name: 'Reply', lucide: 'Reply', keywords: ['reply', 'respond', 'answer', 'message', 'chat'], category: 'Communication' },
  { name: 'AtSign', lucide: 'AtSign', keywords: ['email', 'mention', 'at', 'contact', 'social'], category: 'Communication' },
  { name: 'Rss', lucide: 'Rss', keywords: ['rss', 'feed', 'subscribe', 'blog', 'news', 'updates'], category: 'Communication' },
  { name: 'Voicemail', lucide: 'Voicemail', keywords: ['voicemail', 'message', 'audio', 'call', 'record'], category: 'Communication' },

  // ── Security ──────────────────────────────────────────────────────────────────
  { name: 'Shield', lucide: 'Shield', keywords: ['security', 'protect', 'safe', 'shield', 'defense', 'guard'], category: 'Security' },
  { name: 'ShieldCheck', lucide: 'ShieldCheck', keywords: ['verified', 'secure', 'protected', 'safe', 'trusted'], category: 'Security' },
  { name: 'ShieldAlert', lucide: 'ShieldAlert', keywords: ['warning', 'threat', 'alert', 'security issue', 'danger'], category: 'Security' },
  { name: 'ShieldX', lucide: 'ShieldX', keywords: ['blocked', 'denied', 'security fail', 'breach', 'unsafe'], category: 'Security' },
  { name: 'Lock', lucide: 'Lock', keywords: ['lock', 'secure', 'private', 'password', 'encrypted', 'auth'], category: 'Security' },
  { name: 'Unlock', lucide: 'Unlock', keywords: ['unlock', 'open', 'access', 'password', 'login'], category: 'Security' },
  { name: 'Key', lucide: 'Key', keywords: ['key', 'access', 'password', 'unlock', 'authentication', 'api'], category: 'Security' },
  { name: 'KeyRound', lucide: 'KeyRound', keywords: ['key', 'auth', 'token', 'api key', 'access'], category: 'Security' },
  { name: 'Fingerprint', lucide: 'Fingerprint', keywords: ['fingerprint', 'biometric', 'identity', 'auth', 'verify'], category: 'Security' },
  { name: 'Eye', lucide: 'Eye', keywords: ['view', 'see', 'watch', 'monitor', 'visibility', 'observe'], category: 'Security' },
  { name: 'EyeOff', lucide: 'EyeOff', keywords: ['hidden', 'private', 'invisible', 'hide'], category: 'Security' },
  { name: 'ScanFace', lucide: 'ScanFace', keywords: ['face', 'scan', 'recognition', 'identity', 'biometric'], category: 'Security' },

  // ── Finance ───────────────────────────────────────────────────────────────────
  { name: 'DollarSign', lucide: 'DollarSign', keywords: ['money', 'finance', 'currency', 'dollar', 'payment', 'price'], category: 'Finance' },
  { name: 'Euro', lucide: 'Euro', keywords: ['money', 'euro', 'currency', 'finance', 'europe', 'payment'], category: 'Finance' },
  { name: 'CreditCard', lucide: 'CreditCard', keywords: ['payment', 'card', 'credit', 'finance', 'billing', 'pay'], category: 'Finance' },
  { name: 'Wallet', lucide: 'Wallet', keywords: ['wallet', 'payment', 'money', 'finance', 'balance', 'crypto'], category: 'Finance' },
  { name: 'PiggyBank', lucide: 'PiggyBank', keywords: ['savings', 'bank', 'money', 'finance', 'save', 'deposit'], category: 'Finance' },
  { name: 'Coins', lucide: 'Coins', keywords: ['coins', 'money', 'cash', 'currency', 'crypto', 'change'], category: 'Finance' },
  { name: 'HandCoins', lucide: 'HandCoins', keywords: ['payment', 'tip', 'give money', 'salary', 'funding', 'cash'], category: 'Finance' },
  { name: 'Receipt', lucide: 'Receipt', keywords: ['receipt', 'invoice', 'billing', 'payment', 'transaction'], category: 'Finance' },
  { name: 'LineChart', lucide: 'LineChart', keywords: ['chart', 'analytics', 'trend', 'data', 'growth', 'finance'], category: 'Finance' },
  { name: 'Banknote', lucide: 'Banknote', keywords: ['money', 'cash', 'note', 'currency', 'bill', 'pay'], category: 'Finance' },
  { name: 'BadgeDollarSign', lucide: 'BadgeDollarSign', keywords: ['price', 'sale', 'offer', 'badge', 'deal', 'cost'], category: 'Finance' },

  // ── Commerce ──────────────────────────────────────────────────────────────────
  { name: 'ShoppingCart', lucide: 'ShoppingCart', keywords: ['cart', 'shop', 'buy', 'ecommerce', 'purchase', 'retail'], category: 'Commerce' },
  { name: 'ShoppingBag', lucide: 'ShoppingBag', keywords: ['bag', 'shop', 'purchase', 'ecommerce', 'retail', 'buy'], category: 'Commerce' },
  { name: 'Store', lucide: 'Store', keywords: ['store', 'shop', 'retail', 'market', 'sell', 'commerce'], category: 'Commerce' },
  { name: 'Tag', lucide: 'Tag', keywords: ['tag', 'label', 'price', 'category', 'discount', 'deal'], category: 'Commerce' },
  { name: 'Tags', lucide: 'Tags', keywords: ['tags', 'labels', 'multiple', 'categories', 'filter'], category: 'Commerce' },
  { name: 'Truck', lucide: 'Truck', keywords: ['delivery', 'shipping', 'truck', 'transport', 'logistics'], category: 'Commerce' },
  { name: 'Package', lucide: 'Package', keywords: ['package', 'product', 'box', 'delivery', 'shipping', 'parcel'], category: 'Commerce' },
  { name: 'Package2', lucide: 'Package2', keywords: ['package', 'product', 'box', 'parcel', 'shipping'], category: 'Commerce' },
  { name: 'Barcode', lucide: 'Barcode', keywords: ['barcode', 'scan', 'product', 'sku', 'retail', 'inventory'], category: 'Commerce' },
  { name: 'Gift', lucide: 'Gift', keywords: ['gift', 'present', 'reward', 'bonus', 'coupon', 'promotion'], category: 'Commerce' },
  { name: 'Gem', lucide: 'Gem', keywords: ['gem', 'premium', 'luxury', 'diamond', 'value', 'rare'], category: 'Commerce' },
  { name: 'Warehouse', lucide: 'Warehouse', keywords: ['warehouse', 'storage', 'inventory', 'logistics', 'supply'], category: 'Commerce' },

  // ── Health ────────────────────────────────────────────────────────────────────
  { name: 'Heart', lucide: 'Heart', keywords: ['health', 'love', 'care', 'medical', 'wellness', 'pulse'], category: 'Health' },
  { name: 'HeartPulse', lucide: 'HeartPulse', keywords: ['heartbeat', 'pulse', 'vitals', 'medical', 'ecg', 'monitor'], category: 'Health' },
  { name: 'HeartCrack', lucide: 'HeartCrack', keywords: ['broken heart', 'mental health', 'stress', 'burnout', 'pain'], category: 'Health' },
  { name: 'Stethoscope', lucide: 'Stethoscope', keywords: ['medical', 'doctor', 'health', 'hospital', 'clinic', 'care'], category: 'Health' },
  { name: 'Pill', lucide: 'Pill', keywords: ['medication', 'medicine', 'pill', 'pharmacy', 'health', 'drug'], category: 'Health' },
  { name: 'Syringe', lucide: 'Syringe', keywords: ['injection', 'vaccine', 'medicine', 'medical', 'dose'], category: 'Health' },
  { name: 'Thermometer', lucide: 'Thermometer', keywords: ['temperature', 'fever', 'health', 'medical', 'measure'], category: 'Health' },
  { name: 'Dumbbell', lucide: 'Dumbbell', keywords: ['gym', 'fitness', 'workout', 'exercise', 'strength'], category: 'Health' },
  { name: 'Brain', lucide: 'Brain', keywords: ['brain', 'mind', 'mental health', 'cognitive', 'psychology', 'think'], category: 'Health' },
  { name: 'Bed', lucide: 'Bed', keywords: ['sleep', 'rest', 'bed', 'recovery', 'hospital', 'health'], category: 'Health' },
  { name: 'Moon', lucide: 'Moon', keywords: ['sleep', 'rest', 'night', 'recovery', 'wellness', 'calm'], category: 'Health' },
  { name: 'ClipboardPlus', lucide: 'ClipboardPlus', keywords: ['medical', 'clipboard', 'record', 'patient', 'health', 'notes'], category: 'Health' },

  // ── Education ─────────────────────────────────────────────────────────────────
  { name: 'BookOpen', lucide: 'BookOpen', keywords: ['book', 'read', 'education', 'learn', 'knowledge', 'library'], category: 'Education' },
  { name: 'Book', lucide: 'Book', keywords: ['book', 'read', 'knowledge', 'story', 'study', 'guide'], category: 'Education' },
  { name: 'BookMarked', lucide: 'BookMarked', keywords: ['bookmark', 'reference', 'saved', 'book', 'study'], category: 'Education' },
  { name: 'BookCopy', lucide: 'BookCopy', keywords: ['books', 'library', 'collection', 'multiple', 'reading'], category: 'Education' },
  { name: 'GraduationCap', lucide: 'GraduationCap', keywords: ['graduate', 'degree', 'school', 'university', 'diploma', 'education'], category: 'Education' },
  { name: 'School', lucide: 'School', keywords: ['school', 'building', 'education', 'study', 'campus'], category: 'Education' },
  { name: 'Backpack', lucide: 'Backpack', keywords: ['school', 'student', 'bag', 'education', 'trip'], category: 'Education' },
  { name: 'PenTool', lucide: 'PenTool', keywords: ['design', 'create', 'draw', 'art', 'creative', 'pen'], category: 'Education' },
  { name: 'Pencil', lucide: 'Pencil', keywords: ['write', 'edit', 'pencil', 'draw', 'draft', 'create'], category: 'Education' },
  { name: 'Pen', lucide: 'Pen', keywords: ['pen', 'write', 'sign', 'notes', 'author', 'create'], category: 'Education' },
  { name: 'Calculator', lucide: 'Calculator', keywords: ['calculator', 'math', 'compute', 'numbers', 'finance'], category: 'Education' },
  { name: 'Microscope', lucide: 'Microscope', keywords: ['science', 'research', 'lab', 'biology', 'analyze'], category: 'Education' },
  { name: 'FlaskConical', lucide: 'FlaskConical', keywords: ['flask', 'science', 'lab', 'chemistry', 'experiment'], category: 'Education' },
  { name: 'Languages', lucide: 'Languages', keywords: ['language', 'translation', 'international', 'speak', 'multilingual'], category: 'Education' },
  { name: 'NotebookText', lucide: 'NotebookText', keywords: ['notebook', 'notes', 'study', 'write', 'journal', 'education'], category: 'Education' },

  // ── Tools ─────────────────────────────────────────────────────────────────────
  { name: 'Settings', lucide: 'Settings', keywords: ['settings', 'configuration', 'options', 'gear', 'preferences'], category: 'Tools' },
  { name: 'Settings2', lucide: 'Settings2', keywords: ['settings', 'adjust', 'configure', 'sliders', 'control'], category: 'Tools' },
  { name: 'Wrench', lucide: 'Wrench', keywords: ['wrench', 'fix', 'repair', 'tool', 'maintenance', 'build'], category: 'Tools' },
  { name: 'Hammer', lucide: 'Hammer', keywords: ['hammer', 'build', 'construct', 'tool', 'craft', 'create'], category: 'Tools' },
  { name: 'PencilRuler', lucide: 'PencilRuler', keywords: ['ruler', 'pencil', 'measure', 'design', 'draft', 'tool'], category: 'Tools' },
  { name: 'Scissors', lucide: 'Scissors', keywords: ['scissors', 'cut', 'trim', 'crop', 'design', 'tool'], category: 'Tools' },
  { name: 'Wand2', lucide: 'Wand2', keywords: ['magic', 'wizard', 'ai', 'auto', 'transform', 'generate'], category: 'Tools' },
  { name: 'Workflow', lucide: 'Workflow', keywords: ['workflow', 'process', 'flow', 'automation', 'pipeline'], category: 'Tools' },
  { name: 'Filter', lucide: 'Filter', keywords: ['filter', 'sort', 'search', 'refine', 'narrow', 'criteria'], category: 'Tools' },
  { name: 'SlidersHorizontal', lucide: 'SlidersHorizontal', keywords: ['sliders', 'adjust', 'configure', 'control', 'settings'], category: 'Tools' },
  { name: 'Gauge', lucide: 'Gauge', keywords: ['gauge', 'meter', 'speed', 'performance', 'level', 'progress'], category: 'Tools' },
  { name: 'Puzzle', lucide: 'Puzzle', keywords: ['puzzle', 'plugin', 'extension', 'integrate', 'piece', 'module'], category: 'Tools' },
  { name: 'Component', lucide: 'Component', keywords: ['component', 'ui', 'module', 'block', 'element', 'widget'], category: 'Tools' },
  { name: 'Magnet', lucide: 'Magnet', keywords: ['magnet', 'attract', 'pull', 'engage', 'draw', 'connect'], category: 'Tools' },

  // ── Design ────────────────────────────────────────────────────────────────────
  { name: 'Palette', lucide: 'Palette', keywords: ['color', 'palette', 'design', 'art', 'paint', 'creative'], category: 'Design' },
  { name: 'Paintbrush', lucide: 'Paintbrush', keywords: ['paint', 'brush', 'design', 'art', 'color', 'draw'], category: 'Design' },
  { name: 'Pipette', lucide: 'Pipette', keywords: ['eyedropper', 'color pick', 'sample', 'design', 'color tool'], category: 'Design' },
  { name: 'Eraser', lucide: 'Eraser', keywords: ['erase', 'delete', 'clear', 'undo', 'remove', 'design'], category: 'Design' },
  { name: 'Crop', lucide: 'Crop', keywords: ['crop', 'resize', 'trim', 'cut', 'image', 'design'], category: 'Design' },
  { name: 'Ruler', lucide: 'Ruler', keywords: ['ruler', 'measure', 'size', 'design', 'layout', 'grid'], category: 'Design' },
  { name: 'Frame', lucide: 'Frame', keywords: ['frame', 'canvas', 'design', 'art', 'border', 'layout'], category: 'Design' },
  { name: 'LayoutGrid', lucide: 'LayoutGrid', keywords: ['grid', 'layout', 'design', 'columns', 'masonry'], category: 'Design' },
  { name: 'LayoutTemplate', lucide: 'LayoutTemplate', keywords: ['template', 'layout', 'design', 'page', 'structure'], category: 'Design' },
  { name: 'Grid2X2', lucide: 'Grid2X2', keywords: ['grid', 'four', 'layout', 'design', 'cells', 'squares'], category: 'Design' },
  { name: 'Shapes', lucide: 'Shapes', keywords: ['shapes', 'design', 'objects', 'elements', 'vector', 'art'], category: 'Design' },
  { name: 'PenLine', lucide: 'PenLine', keywords: ['pen', 'line', 'draw', 'path', 'vector', 'design'], category: 'Design' },
  { name: 'Type', lucide: 'Type', keywords: ['text', 'font', 'typography', 'type', 'letter', 'design'], category: 'Design' },
  { name: 'Contrast', lucide: 'Contrast', keywords: ['contrast', 'accessibility', 'dark light', 'design', 'balance'], category: 'Design' },

  // ── Media ─────────────────────────────────────────────────────────────────────
  { name: 'Image', lucide: 'Image', keywords: ['image', 'photo', 'picture', 'media', 'gallery'], category: 'Media' },
  { name: 'Images', lucide: 'Images', keywords: ['images', 'photos', 'gallery', 'collection', 'album'], category: 'Media' },
  { name: 'Camera', lucide: 'Camera', keywords: ['camera', 'photo', 'picture', 'capture', 'snapshot'], category: 'Media' },
  { name: 'Video', lucide: 'Video', keywords: ['video', 'film', 'movie', 'record', 'media', 'stream'], category: 'Media' },
  { name: 'Film', lucide: 'Film', keywords: ['film', 'movie', 'cinema', 'video', 'reel', 'production'], category: 'Media' },
  { name: 'Clapperboard', lucide: 'Clapperboard', keywords: ['film', 'movie', 'production', 'video', 'cinema', 'action'], category: 'Media' },
  { name: 'Music', lucide: 'Music', keywords: ['music', 'audio', 'sound', 'song', 'entertainment', 'play'], category: 'Media' },
  { name: 'Music2', lucide: 'Music2', keywords: ['music', 'note', 'audio', 'song', 'melody'], category: 'Media' },
  { name: 'Mic', lucide: 'Mic', keywords: ['microphone', 'record', 'audio', 'voice', 'podcast', 'speak'], category: 'Media' },
  { name: 'Podcast', lucide: 'Podcast', keywords: ['podcast', 'audio', 'broadcast', 'radio', 'stream'], category: 'Media' },
  { name: 'Radio', lucide: 'Radio', keywords: ['radio', 'broadcast', 'stream', 'fm', 'audio', 'listen'], category: 'Media' },
  { name: 'Tv', lucide: 'Tv', keywords: ['tv', 'television', 'screen', 'watch', 'broadcast', 'stream'], category: 'Media' },
  { name: 'Play', lucide: 'Play', keywords: ['play', 'start', 'media', 'video', 'audio', 'stream'], category: 'Media' },
  { name: 'Pause', lucide: 'Pause', keywords: ['pause', 'stop', 'media', 'player', 'wait'], category: 'Media' },
  { name: 'Volume2', lucide: 'Volume2', keywords: ['volume', 'sound', 'audio', 'speaker', 'loud'], category: 'Media' },
  { name: 'Headphones', lucide: 'Headphones', keywords: ['headphones', 'audio', 'listen', 'music', 'sound'], category: 'Media' },

  // ── Social ────────────────────────────────────────────────────────────────────
  { name: 'Share2', lucide: 'Share2', keywords: ['share', 'social', 'spread', 'network', 'connect'], category: 'Social' },
  { name: 'ThumbsUp', lucide: 'ThumbsUp', keywords: ['like', 'approve', 'positive', 'thumbs up', 'good'], category: 'Social' },
  { name: 'ThumbsDown', lucide: 'ThumbsDown', keywords: ['dislike', 'disapprove', 'negative', 'bad', 'reject'], category: 'Social' },
  { name: 'Bookmark', lucide: 'Bookmark', keywords: ['bookmark', 'save', 'favorite', 'collection', 'remember'], category: 'Social' },
  { name: 'Link', lucide: 'Link', keywords: ['link', 'url', 'connect', 'chain', 'web', 'hyperlink'], category: 'Social' },
  { name: 'Link2', lucide: 'Link2', keywords: ['link', 'url', 'share', 'connect', 'web'], category: 'Social' },
  { name: 'MessageCircleHeart', lucide: 'MessageCircleHeart', keywords: ['love', 'chat', 'affection', 'care', 'message', 'support'], category: 'Social' },
  { name: 'UserRoundPlus', lucide: 'UserRoundPlus', keywords: ['follow', 'add', 'connect', 'friend', 'invite', 'social'], category: 'Social' },
  { name: 'Trophy', lucide: 'Trophy', keywords: ['trophy', 'leaderboard', 'achievement', 'winner', 'rank'], category: 'Social' },
  { name: 'PartyPopper', lucide: 'PartyPopper', keywords: ['party', 'celebrate', 'confetti', 'event', 'cheer', 'social'], category: 'Social' },
  { name: 'Laugh', lucide: 'Laugh', keywords: ['laugh', 'funny', 'emoji', 'reaction', 'happy', 'social'], category: 'Social' },
  { name: 'BadgeCheck', lucide: 'BadgeCheck', keywords: ['verified', 'badge', 'check', 'certified', 'authentic', 'social'], category: 'Social' },

  // ── Nature ────────────────────────────────────────────────────────────────────
  { name: 'Sun', lucide: 'Sun', keywords: ['sun', 'light', 'bright', 'day', 'weather', 'energy', 'solar'], category: 'Nature' },
  { name: 'SunMedium', lucide: 'SunMedium', keywords: ['sun', 'brightness', 'light', 'warm', 'day'], category: 'Nature' },
  { name: 'CloudRain', lucide: 'CloudRain', keywords: ['rain', 'weather', 'cloud', 'storm', 'wet', 'forecast'], category: 'Nature' },
  { name: 'CloudLightning', lucide: 'CloudLightning', keywords: ['storm', 'thunder', 'lightning', 'weather', 'power'], category: 'Nature' },
  { name: 'CloudSnow', lucide: 'CloudSnow', keywords: ['snow', 'winter', 'cold', 'weather', 'blizzard', 'freeze'], category: 'Nature' },
  { name: 'Tornado', lucide: 'Tornado', keywords: ['tornado', 'storm', 'wind', 'weather', 'spiral', 'nature'], category: 'Nature' },
  { name: 'Droplets', lucide: 'Droplets', keywords: ['water', 'drops', 'rain', 'hydration', 'liquid', 'clean'], category: 'Nature' },
  { name: 'Leaf', lucide: 'Leaf', keywords: ['eco', 'green', 'nature', 'environment', 'organic', 'sustainable'], category: 'Nature' },
  { name: 'Flower2', lucide: 'Flower2', keywords: ['flower', 'nature', 'bloom', 'spring', 'beauty', 'garden'], category: 'Nature' },
  { name: 'TreePine', lucide: 'TreePine', keywords: ['tree', 'forest', 'nature', 'eco', 'pine', 'green'], category: 'Nature' },
  { name: 'Trees', lucide: 'Trees', keywords: ['trees', 'forest', 'park', 'nature', 'green', 'woodland'], category: 'Nature' },
  { name: 'Mountain', lucide: 'Mountain', keywords: ['mountain', 'peak', 'climb', 'nature', 'landscape', 'hiking'], category: 'Nature' },
  { name: 'Sprout', lucide: 'Sprout', keywords: ['sprout', 'grow', 'plant', 'nature', 'new', 'green'], category: 'Nature' },
  { name: 'Bug', lucide: 'Bug', keywords: ['bug', 'insect', 'nature', 'animal', 'creature', 'small'], category: 'Nature' },
  { name: 'Bird', lucide: 'Bird', keywords: ['bird', 'fly', 'nature', 'animal', 'wing', 'tweet'], category: 'Nature' },
  { name: 'Fish', lucide: 'Fish', keywords: ['fish', 'sea', 'ocean', 'nature', 'water', 'animal'], category: 'Nature' },
  { name: 'Shell', lucide: 'Shell', keywords: ['shell', 'ocean', 'sea', 'nature', 'beach', 'spiral'], category: 'Nature' },

  // ── Food & Drink ──────────────────────────────────────────────────────────────
  { name: 'Coffee', lucide: 'Coffee', keywords: ['coffee', 'cafe', 'drink', 'morning', 'hot', 'espresso'], category: 'Food & Drink' },
  { name: 'Utensils', lucide: 'Utensils', keywords: ['food', 'restaurant', 'eat', 'fork', 'knife', 'dining'], category: 'Food & Drink' },
  { name: 'UtensilsCrossed', lucide: 'UtensilsCrossed', keywords: ['restaurant', 'dining', 'food', 'eat', 'kitchen'], category: 'Food & Drink' },
  { name: 'Pizza', lucide: 'Pizza', keywords: ['pizza', 'food', 'italian', 'cheese', 'fast food', 'slice'], category: 'Food & Drink' },
  { name: 'Cookie', lucide: 'Cookie', keywords: ['cookie', 'bake', 'dessert', 'sweet', 'snack', 'food'], category: 'Food & Drink' },
  { name: 'Cake', lucide: 'Cake', keywords: ['cake', 'birthday', 'dessert', 'sweet', 'celebrate', 'bake'], category: 'Food & Drink' },
  { name: 'IceCreamCone', lucide: 'IceCreamCone', keywords: ['ice cream', 'dessert', 'sweet', 'summer', 'food'], category: 'Food & Drink' },
  { name: 'Apple', lucide: 'Apple', keywords: ['apple', 'fruit', 'food', 'health', 'eat', 'snack'], category: 'Food & Drink' },
  { name: 'Salad', lucide: 'Salad', keywords: ['salad', 'healthy', 'food', 'vegetables', 'green', 'eat'], category: 'Food & Drink' },
  { name: 'Soup', lucide: 'Soup', keywords: ['soup', 'bowl', 'food', 'warm', 'meal', 'cook'], category: 'Food & Drink' },
  { name: 'Wine', lucide: 'Wine', keywords: ['wine', 'drink', 'alcohol', 'glass', 'bar', 'celebrate'], category: 'Food & Drink' },
  { name: 'Beer', lucide: 'Beer', keywords: ['beer', 'drink', 'alcohol', 'bar', 'pub', 'brew'], category: 'Food & Drink' },
  { name: 'Milk', lucide: 'Milk', keywords: ['milk', 'drink', 'dairy', 'nutrition', 'food', 'healthy'], category: 'Food & Drink' },
  { name: 'ChefHat', lucide: 'ChefHat', keywords: ['chef', 'cook', 'food', 'restaurant', 'kitchen', 'culinary'], category: 'Food & Drink' },
  { name: 'Beef', lucide: 'Beef', keywords: ['meat', 'beef', 'steak', 'food', 'grill', 'protein'], category: 'Food & Drink' },
  { name: 'Carrot', lucide: 'Carrot', keywords: ['carrot', 'vegetable', 'food', 'healthy', 'orange', 'cook'], category: 'Food & Drink' },
  { name: 'Egg', lucide: 'Egg', keywords: ['egg', 'breakfast', 'food', 'cook', 'protein', 'farm'], category: 'Food & Drink' },

  // ── Travel ────────────────────────────────────────────────────────────────────
  { name: 'Plane', lucide: 'Plane', keywords: ['plane', 'flight', 'travel', 'airline', 'fly', 'airport'], category: 'Travel' },
  { name: 'PlaneTakeoff', lucide: 'PlaneTakeoff', keywords: ['takeoff', 'flight', 'travel', 'departure', 'airline'], category: 'Travel' },
  { name: 'Car', lucide: 'Car', keywords: ['car', 'drive', 'vehicle', 'auto', 'transport', 'road'], category: 'Travel' },
  { name: 'Train', lucide: 'Train', keywords: ['train', 'rail', 'travel', 'transport', 'subway', 'commute'], category: 'Travel' },
  { name: 'Bus', lucide: 'Bus', keywords: ['bus', 'transport', 'travel', 'commute', 'public', 'vehicle'], category: 'Travel' },
  { name: 'Bike', lucide: 'Bike', keywords: ['bike', 'bicycle', 'cycle', 'sport', 'transport', 'eco'], category: 'Travel' },
  { name: 'Ship', lucide: 'Ship', keywords: ['ship', 'boat', 'cruise', 'sea', 'travel', 'ocean'], category: 'Travel' },
  { name: 'Sailboat', lucide: 'Sailboat', keywords: ['sailboat', 'sail', 'sea', 'wind', 'boat', 'ocean'], category: 'Travel' },
  { name: 'Luggage', lucide: 'Luggage', keywords: ['luggage', 'suitcase', 'travel', 'trip', 'bag', 'vacation'], category: 'Travel' },
  { name: 'Hotel', lucide: 'Hotel', keywords: ['hotel', 'accommodation', 'stay', 'travel', 'room', 'book'], category: 'Travel' },
  { name: 'Tent', lucide: 'Tent', keywords: ['tent', 'camping', 'outdoor', 'nature', 'adventure', 'hike'], category: 'Travel' },
  { name: 'Sunrise', lucide: 'Sunrise', keywords: ['sunrise', 'dawn', 'morning', 'travel', 'beach', 'horizon'], category: 'Travel' },

  // ── Productivity ──────────────────────────────────────────────────────────────
  { name: 'Clock', lucide: 'Clock', keywords: ['time', 'clock', 'schedule', 'timer', 'hour', 'deadline'], category: 'Productivity' },
  { name: 'Clock4', lucide: 'Clock4', keywords: ['time', 'clock', 'schedule', 'deadline', 'hour'], category: 'Productivity' },
  { name: 'Calendar', lucide: 'Calendar', keywords: ['calendar', 'date', 'schedule', 'event', 'plan'], category: 'Productivity' },
  { name: 'CalendarDays', lucide: 'CalendarDays', keywords: ['calendar', 'days', 'schedule', 'planner', 'month', 'event'], category: 'Productivity' },
  { name: 'CalendarCheck', lucide: 'CalendarCheck', keywords: ['booked', 'confirmed', 'scheduled', 'appointment', 'done'], category: 'Productivity' },
  { name: 'Timer', lucide: 'Timer', keywords: ['timer', 'countdown', 'pomodoro', 'time', 'track', 'stop'], category: 'Productivity' },
  { name: 'AlarmClock', lucide: 'AlarmClock', keywords: ['alarm', 'wake', 'reminder', 'clock', 'time', 'alert'], category: 'Productivity' },
  { name: 'CheckCircle', lucide: 'CheckCircle', keywords: ['done', 'complete', 'check', 'success', 'approve', 'task'], category: 'Productivity' },
  { name: 'CheckSquare', lucide: 'CheckSquare', keywords: ['checkbox', 'todo', 'done', 'task', 'complete'], category: 'Productivity' },
  { name: 'ListTodo', lucide: 'ListTodo', keywords: ['todo', 'task', 'list', 'check', 'planner', 'actions'], category: 'Productivity' },
  { name: 'StickyNote', lucide: 'StickyNote', keywords: ['note', 'sticky', 'memo', 'reminder', 'write', 'idea'], category: 'Productivity' },
  { name: 'Archive', lucide: 'Archive', keywords: ['archive', 'store', 'file', 'organize', 'save', 'backup'], category: 'Productivity' },
  { name: 'Folder', lucide: 'Folder', keywords: ['folder', 'directory', 'organize', 'files', 'storage'], category: 'Productivity' },
  { name: 'FolderOpen', lucide: 'FolderOpen', keywords: ['folder', 'open', 'browse', 'files', 'directory'], category: 'Productivity' },
  { name: 'FileEdit', lucide: 'FileEdit', keywords: ['edit', 'document', 'modify', 'draft', 'write', 'update'], category: 'Productivity' },
  { name: 'Kanban', lucide: 'Kanban', keywords: ['kanban', 'board', 'tasks', 'agile', 'workflow', 'sprint'], category: 'Productivity' },

  // ── Navigation ────────────────────────────────────────────────────────────────
  { name: 'Home', lucide: 'Home', keywords: ['home', 'house', 'main', 'dashboard', 'start', 'base'], category: 'Navigation' },
  { name: 'Search', lucide: 'Search', keywords: ['search', 'find', 'discover', 'look', 'magnify', 'explore'], category: 'Navigation' },
  { name: 'LayoutDashboard', lucide: 'LayoutDashboard', keywords: ['dashboard', 'layout', 'admin', 'panel', 'overview'], category: 'Navigation' },
  { name: 'LayoutList', lucide: 'LayoutList', keywords: ['list', 'layout', 'items', 'rows', 'feed', 'view'], category: 'Navigation' },
  { name: 'Menu', lucide: 'Menu', keywords: ['menu', 'hamburger', 'navigation', 'sidebar', 'toggle'], category: 'Navigation' },
  { name: 'Sidebar', lucide: 'Sidebar', keywords: ['sidebar', 'panel', 'menu', 'navigation', 'left', 'layout'], category: 'Navigation' },
  { name: 'Rocket', lucide: 'Rocket', keywords: ['launch', 'startup', 'fast', 'rocket', 'blast', 'deploy'], category: 'Navigation' },
  { name: 'Flag', lucide: 'Flag', keywords: ['flag', 'goal', 'milestone', 'mark', 'finish', 'mission'], category: 'Navigation' },
  { name: 'ArrowUpRight', lucide: 'ArrowUpRight', keywords: ['external', 'link', 'go', 'open', 'launch', 'outbound'], category: 'Navigation' },
  { name: 'ExternalLink', lucide: 'ExternalLink', keywords: ['external', 'link', 'open', 'new tab', 'navigate'], category: 'Navigation' },
  { name: 'ChevronRight', lucide: 'ChevronRight', keywords: ['next', 'forward', 'arrow', 'breadcrumb', 'navigation'], category: 'Navigation' },
  { name: 'MoreHorizontal', lucide: 'MoreHorizontal', keywords: ['more', 'options', 'dots', 'menu', 'extra', 'kebab'], category: 'Navigation' },
  ...GAME_ICONS_ABSTRACT
]

// ── Search helper ─────────────────────────────────────────────────────────────

export function searchIcons(query: string, category?: string): IconEntry[] {
  const q = query.toLowerCase().trim()
  let icons = ICON_LIBRARY

  if (category && category !== 'All') {
    icons = icons.filter((i) => i.category === category)
  }

  if (!q) return icons

  return icons
    .map((icon) => {
      let score = 0
      if (icon.name.toLowerCase() === q) score = 100
      else if (icon.name.toLowerCase().startsWith(q)) score = 80
      else if (icon.name.toLowerCase().includes(q)) score = 60
      else if (icon.keywords.some((k) => k === q)) score = 50
      else if (icon.keywords.some((k) => k.startsWith(q))) score = 30
      else if (icon.keywords.some((k) => k.includes(q))) score = 10
      return { icon, score }
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((x) => x.icon)
}
